import Link from 'next/link'

export default function DMCAPage() {
  return (
    <div className="min-h-screen bg-[#0B1120] text-white">
      <div className="max-w-3xl mx-auto px-6 py-16 prose prose-invert prose-sm">
        <Link href="/legal" className="text-sky-400 text-sm hover:underline no-underline">← Retour</Link>

        <h1>DMCA &amp; Copyright Policy / Notification de droits d&apos;auteur</h1>
        <p className="text-gray-400 text-sm">Last updated: 2026-04-17 · v2 · EN/FR bilingual, English prevails</p>

        <p>
          Feel The Gap (operated by OFA Holdings LLC) respects the intellectual property rights of third parties and expects
          its Customers to do the same. We respond to notices of alleged infringement that comply with the United States
          Digital Millennium Copyright Act (17 U.S.C. § 512) and, for EU users, the EU Digital Services Act
          (Regulation 2022/2065) and the Copyright in the Digital Single Market Directive (2019/790).
        </p>

        <h2>1. Designated Agent / Agent désigné</h2>
        <p>
          Notifications of claimed copyright infringement must be sent to our Designated Agent:<br />
          <strong>DMCA Agent, Feel The Gap (OFA Holdings LLC)</strong><br />
          30 N Gould St, Ste R, Sheridan, WY 82801, USA<br />
          Email: <strong>dmca@feelthegap.world</strong>
        </p>
        <p className="text-xs text-gray-400">
          A copy of this agent designation is on file with the U.S. Copyright Office pursuant to 17 U.S.C. § 512(c)(2).
          Physical mail is accepted but electronic notice is strongly preferred and processed faster.
        </p>

        <h2>2. Notice Requirements / Contenu de la notification</h2>
        <p>To be effective under 17 U.S.C. § 512(c)(3), your notification must include all of the following:</p>
        <ol>
          <li>A physical or electronic signature of the copyright owner or a person authorised to act on their behalf</li>
          <li>Identification of the copyrighted work(s) claimed to have been infringed</li>
          <li>Identification of the allegedly infringing material and its precise location (URL, export filename, or generated-plan ID) on the Service</li>
          <li>Your contact information: full name, postal address, telephone, and email</li>
          <li>A statement that you have a good-faith belief that the use is not authorised by the owner, its agent, or the law</li>
          <li>A statement, under penalty of perjury, that the information in the notice is accurate and that you are authorised to act on behalf of the owner</li>
        </ol>

        <h2>3. Counter-Notification / Contre-notification</h2>
        <p>
          If you believe your content was wrongly removed, you may file a counter-notification containing: your signature,
          identification of the removed material, a statement under penalty of perjury that removal resulted from mistake or
          misidentification, your contact information, and your consent to the jurisdiction of the U.S. District Court for
          the District of Wyoming (or, if you reside outside the U.S., any district where OFA Holdings LLC may be found).
          We forward valid counter-notifications to the original claimant and may restore the content after 10–14 business days
          unless we receive notice of a lawsuit.
        </p>

        <h2>4. Data Provenance &amp; Third-Party Datasets</h2>
        <p>
          FTG curates publicly-available trade data from sources including UN Comtrade, OEC mirrors, EUR-Lex, USDA,
          ITC Trade Map open endpoints, national customs offices, and official statistics agencies. We believe our aggregation,
          structuring, and visualisation of this data are covered by the sui generis database right (EU Directive 96/9/EC)
          and US hot-news / fair-use principles respectively, but we remove or redact specific records on a documented request
          from the original source when a bona fide dispute exists. Such requests should be sent to <strong>dmca@feelthegap.world</strong>
          with the record identifier(s), the underlying source, and the legal basis invoked.
        </p>

        <h2>5. AI-Generated Output &amp; Copyright</h2>
        <p>
          Business plans, roadmaps, and advisor responses are generated by AI models from prompts and the FTG dataset.
          Customer owns the specific Output generated for their business, subject to third-party rights in any underlying
          pre-existing works. If you believe AI Output reproduces material parts of your copyrighted work, send a notification
          per §2 above and we will remove it from the Customer&apos;s account, re-generate an alternative, and evaluate whether
          an upstream model or a specific prompt should be sanitised or blocked.
        </p>

        <h2>6. Repeat Infringers / Récidivistes</h2>
        <p>
          We terminate, in appropriate circumstances, the accounts of Customers who are repeat infringers. A Customer
          accumulating three or more substantiated DMCA notices within any rolling 12-month period will have their account
          suspended, exports revoked, and any remaining pre-paid balance forfeited.
        </p>

        <h2>7. EU Digital Services Act Notices</h2>
        <p>
          EU users may submit illegal-content notices via the same email. We confirm receipt within 48 hours and decide
          within 7 days for clearly illegal content, 14 days otherwise, with written reasons and appeal rights as required by
          Articles 16 and 17 of the DSA. Our statement of reasons is also filed with the Commission&apos;s Transparency Database
          where applicable. Disputes may be escalated to a certified out-of-court dispute-settlement body under Article 21 DSA.
        </p>

        <h2>8. False Claims / Fausses déclarations</h2>
        <p>
          Under 17 U.S.C. § 512(f), any person who knowingly materially misrepresents that material is infringing may be liable
          for damages, including costs and attorneys&apos; fees. We reserve the right to seek recovery for bad-faith notices and
          to share such notices, redacted where appropriate, with the affected Customer.
        </p>

        <h2>9. Contact</h2>
        <p>
          DMCA / DSA notices: <strong>dmca@feelthegap.world</strong>.<br />
          General legal inquiries: <strong>legal@feelthegap.world</strong>.
        </p>
      </div>
    </div>
  )
}
