// ── CMS Collection Registry ─────────────────────────────────────────────────
// Defines what content blocks exist per site/collection.
// The admin UI reads this to render forms; the seed script uses defaults.

export interface SlotDef {
  slug: string;
  label: string;
  field_type: "text" | "richtext" | "number" | "image" | "video" | "json";
  default_en: string;
  default_fr: string;
}

export interface CollectionDef {
  key: string;
  label: string;
  slots: SlotDef[];
}

export interface SiteDef {
  key: string;
  label: string;
  collections: CollectionDef[];
}

// ── Feel The Gap ────────────────────────────────────────────────────────────

const ftgLanding: CollectionDef = {
  key: "landing",
  label: "Page d'accueil",
  slots: [
    { slug: "badge", label: "Badge hero", field_type: "text", default_fr: "Plateforme SaaS · Données mondiales import/export", default_en: "SaaS Platform · Global import/export data" },
    { slug: "hero_title", label: "Titre hero", field_type: "text", default_fr: "Trouvez où vendre", default_en: "Find where to sell" },
    { slug: "hero_title_accent", label: "Titre hero (accent)", field_type: "text", default_fr: "avant tout le monde", default_en: "before everyone else" },
    { slug: "hero_desc", label: "Description hero", field_type: "richtext", default_fr: "Feel The Gap analyse les flux commerciaux mondiaux pour identifier les marchés sous-approvisionnés. IA, données réelles, business plans actionnables.", default_en: "Feel The Gap analyses global trade flows to identify under-supplied markets. AI, real data, actionable business plans." },
    { slug: "stat_1_value", label: "Stat 1 — Valeur", field_type: "text", default_fr: "195", default_en: "195" },
    { slug: "stat_1_label", label: "Stat 1 — Label", field_type: "text", default_fr: "Pays couverts", default_en: "Countries covered" },
    { slug: "stat_2_value", label: "Stat 2 — Valeur", field_type: "text", default_fr: "500+", default_en: "500+" },
    { slug: "stat_2_label", label: "Stat 2 — Label", field_type: "text", default_fr: "Catégories de produits", default_en: "Product categories" },
    { slug: "stat_3_value", label: "Stat 3 — Valeur", field_type: "text", default_fr: "AI", default_en: "AI" },
    { slug: "stat_3_label", label: "Stat 3 — Label", field_type: "text", default_fr: "Propulsé par Gemini", default_en: "Powered by Gemini" },
    { slug: "features_title", label: "Titre section features", field_type: "text", default_fr: "De la data brute aux opportunités actionnables", default_en: "From raw data to actionable opportunities" },
    { slug: "f1_title", label: "Feature 1 — Titre", field_type: "text", default_fr: "Carte mondiale des flux", default_en: "Global trade flow map" },
    { slug: "f1_desc", label: "Feature 1 — Description", field_type: "richtext", default_fr: "Visualisez les gaps d'import/export pays par pays. Identifiez où la demande dépasse l'offre locale.", default_en: "Visualise import/export gaps country by country. Identify where demand exceeds local supply." },
    { slug: "f2_title", label: "Feature 2 — Titre", field_type: "text", default_fr: "Opportunity Farming", default_en: "Opportunity Farming" },
    { slug: "f2_desc", label: "Feature 2 — Description", field_type: "richtext", default_fr: "Scannez votre produit. L'IA identifie les typologies de clients, les géographies et les canaux de distribution.", default_en: "Scan your product. AI identifies customer profiles, geographies and distribution channels." },
    { slug: "f3_title", label: "Feature 3 — Titre", field_type: "text", default_fr: "Business plans IA", default_en: "AI business plans" },
    { slug: "f3_desc", label: "Feature 3 — Description", field_type: "richtext", default_fr: "De l'idée au plan d'action. Capex, Opex, ROI, fournisseurs recommandés — tout généré par l'IA en quelques secondes.", default_en: "From idea to action plan. Capex, Opex, ROI, recommended suppliers — all generated by AI in seconds." },
    { slug: "f4_title", label: "Feature 4 — Titre", field_type: "text", default_fr: "Réseau d'influence", default_en: "Influencer network" },
    { slug: "f4_desc", label: "Feature 4 — Description", field_type: "richtext", default_fr: "Connectez vos produits à des influenceurs qualifiés. Liens affiliés trackés, paiements automatiques via Stripe.", default_en: "Connect your products to qualified influencers. Tracked affiliate links, automatic payouts via Stripe." },
    { slug: "cta_final_title", label: "CTA final — Titre", field_type: "text", default_fr: "Prêt à identifier votre prochain marché ?", default_en: "Ready to identify your next market?" },
    { slug: "cta_final_desc", label: "CTA final — Description", field_type: "text", default_fr: "Inscription gratuite. Aucune carte bancaire requise.", default_en: "Free registration. No credit card required." },
    { slug: "cta_final_btn", label: "CTA final — Bouton", field_type: "text", default_fr: "Créer mon compte →", default_en: "Create my account →" },
  ],
};

const ftgPricing: CollectionDef = {
  key: "pricing",
  label: "Page tarifs",
  slots: [
    { slug: "plan_explorer_name", label: "Explorer — Nom", field_type: "text", default_fr: "Explorer", default_en: "Explorer" },
    { slug: "plan_explorer_price", label: "Explorer — Prix", field_type: "text", default_fr: "Gratuit", default_en: "Free" },
    { slug: "plan_explorer_features", label: "Explorer — Features", field_type: "json", default_fr: '["Carte mondiale interactive","Scores d\'opportunité basiques","1 rapport pays gratuit / mois"]', default_en: '["Interactive world map","Basic opportunity scores","1 free country report / month"]' },
    { slug: "plan_data_name", label: "Data — Nom", field_type: "text", default_fr: "Data", default_en: "Data" },
    { slug: "plan_data_price", label: "Data — Prix", field_type: "text", default_fr: "29 €/mois", default_en: "€29/month" },
    { slug: "plan_data_features", label: "Data — Features", field_type: "json", default_fr: '["Recherches sauvegardées","Matérialisation des opportunités","Export CSV","Alertes email"]', default_en: '["Saved searches","Opportunity materialization","CSV export","Email alerts"]' },
    { slug: "plan_strategy_name", label: "Strategy — Nom", field_type: "text", default_fr: "Strategy", default_en: "Strategy" },
    { slug: "plan_strategy_price", label: "Strategy — Prix", field_type: "text", default_fr: "99 €/mois", default_en: "€99/month" },
    { slug: "plan_strategy_features", label: "Strategy — Features", field_type: "json", default_fr: '["Business plans IA","AI Trade Advisor","Farming scanner","Crédits IA inclus","Onboarding 1-on-1"]', default_en: '["AI business plans","AI Trade Advisor","Farming scanner","AI credits included","1-on-1 onboarding"]' },
    { slug: "plan_premium_name", label: "Premium — Nom", field_type: "text", default_fr: "Premium", default_en: "Premium" },
    { slug: "plan_premium_price", label: "Premium — Prix", field_type: "text", default_fr: "149 €/mois", default_en: "€149/month" },
    { slug: "plan_premium_features", label: "Premium — Features", field_type: "json", default_fr: '["Réseau influenceurs","Geo-matching","Dashboard affiliation","Sales map"]', default_en: '["Influencer network","Geo-matching","Affiliate dashboard","Sales map"]' },
  ],
};

// ── Shift Dynamics ──────────────────────────────────────────────────────────

const shiftHome: CollectionDef = {
  key: "home",
  label: "Page d'accueil",
  slots: [
    { slug: "hero_badge", label: "Badge hero", field_type: "text", default_fr: "Conseil stratégique & technologique", default_en: "Strategic & Technology Consulting" },
    { slug: "hero_title", label: "Titre hero", field_type: "text", default_fr: "Transformez vos marchés", default_en: "Transform your markets" },
    { slug: "hero_subtitle", label: "Sous-titre hero", field_type: "richtext", default_fr: "22 ans d'expertise en deep tech, gaming et expansion internationale.", default_en: "22 years of expertise in deep tech, gaming and international expansion." },
    { slug: "stat_revenue", label: "Stat — Revenue", field_type: "text", default_fr: ">100M€", default_en: ">€100M" },
    { slug: "stat_countries", label: "Stat — Pays", field_type: "text", default_fr: "44", default_en: "44" },
    { slug: "stat_markets", label: "Stat — Marchés", field_type: "text", default_fr: "17", default_en: "17" },
  ],
};

const shiftAbout: CollectionDef = {
  key: "about",
  label: "Page À propos",
  slots: [
    { slug: "experience_years", label: "Années d'expérience", field_type: "number", default_fr: "22", default_en: "22" },
    { slug: "countries_covered", label: "Pays couverts", field_type: "number", default_fr: "44", default_en: "44" },
    { slug: "gaming_markets", label: "Marchés gaming", field_type: "number", default_fr: "17", default_en: "17" },
    { slug: "players_euro", label: "Players EURO 2016", field_type: "text", default_fr: "70K+", default_en: "70K+" },
    { slug: "quote", label: "Citation", field_type: "richtext", default_fr: "La technologie n'a de valeur que lorsqu'elle génère du revenu mesurable.", default_en: "Technology is only as valuable as the measurable revenue it generates." },
  ],
};

// ── The Estate ──────────────────────────────────────────────────────────────

const estateDashboard: CollectionDef = {
  key: "dashboard",
  label: "Dashboard",
  slots: [
    { slug: "services", label: "Services monitorés", field_type: "json", default_fr: '[{"name":"The Estate","icon":"🏨","color":"#C9A84C"},{"name":"Shift Dynamics","icon":"⚡","color":"#8B5CF6"},{"name":"Feel The Gap","icon":"🌍","color":"#3B82F6"},{"name":"Command Center","icon":"🎙️","color":"#10B981"}]', default_en: '[{"name":"The Estate","icon":"🏨","color":"#C9A84C"},{"name":"Shift Dynamics","icon":"⚡","color":"#8B5CF6"},{"name":"Feel The Gap","icon":"🌍","color":"#3B82F6"},{"name":"Command Center","icon":"🎙️","color":"#10B981"}]' },
    { slug: "tier_labels", label: "Labels des tiers", field_type: "json", default_fr: '{"explorer":"Explorer","data":"Data","strategy":"Strategy","premium":"Premium","enterprise":"Enterprise"}', default_en: '{"explorer":"Explorer","data":"Data","strategy":"Strategy","premium":"Premium","enterprise":"Enterprise"}' },
    { slug: "tier_colors", label: "Couleurs des tiers", field_type: "json", default_fr: '{"explorer":"#5A6A7A","data":"#3B82F6","strategy":"#8B5CF6","premium":"#C9A84C","enterprise":"#10B981"}', default_en: '{"explorer":"#5A6A7A","data":"#3B82F6","strategy":"#8B5CF6","premium":"#C9A84C","enterprise":"#10B981"}' },
  ],
};

// ── Export ───────────────────────────────────────────────────────────────────

export const CMS_SITES: SiteDef[] = [
  { key: "ftg", label: "Feel The Gap", collections: [ftgLanding, ftgPricing] },
  { key: "shift", label: "Shift Dynamics", collections: [shiftHome, shiftAbout] },
  { key: "estate", label: "The Estate", collections: [estateDashboard] },
];

/** Find a slot definition */
export function findSlot(siteKey: string, collectionKey: string, slug: string): SlotDef | undefined {
  const site = CMS_SITES.find((s) => s.key === siteKey);
  const coll = site?.collections.find((c) => c.key === collectionKey);
  return coll?.slots.find((s) => s.slug === slug);
}
