// ── CMS Collection Registry ─────────────────────────────────────────────────
// Defines what content blocks exist per site/collection.
// The admin UI reads this to render forms; the seed script uses defaults.
// This file mirrors /root/command-center/lib/cms-collections.ts

export interface SlotDef {
  slug: string;
  label: string;
  field_type: "text" | "richtext" | "number" | "image" | "video" | "json";
  default_en: string;
  default_fr: string;
}

export interface CollectionDef {
  key: string;
  label: string;
  slots: SlotDef[];
}

export interface SiteDef {
  key: string;
  label: string;
  icon?: string;
  color?: string;
  collections: CollectionDef[];
}

// ── Feel The Gap ────────────────────────────────────────────────────────────

const ftgLanding: CollectionDef = {
  key: "landing",
  label: "Page d'accueil",
  slots: [
    { slug: "badge", label: "Badge hero", field_type: "text", default_fr: "Plateforme SaaS · Données mondiales import/export", default_en: "SaaS Platform · Global import/export data" },
    { slug: "hero_title", label: "Titre hero", field_type: "text", default_fr: "Trouvez où vendre", default_en: "Find where to sell" },
    { slug: "hero_title_accent", label: "Titre hero (accent)", field_type: "text", default_fr: "avant tout le monde", default_en: "before everyone else" },
    { slug: "hero_desc", label: "Description hero", field_type: "richtext", default_fr: "Feel The Gap analyse les flux commerciaux mondiaux pour identifier les marchés sous-approvisionnés. IA, données réelles, business plans actionnables.", default_en: "Feel The Gap analyses global trade flows to identify under-supplied markets. AI, real data, actionable business plans." },
    { slug: "stat_1_value", label: "Stat 1 — Valeur", field_type: "text", default_fr: "195", default_en: "195" },
    { slug: "stat_1_label", label: "Stat 1 — Label", field_type: "text", default_fr: "Pays couverts", default_en: "Countries covered" },
    { slug: "stat_2_value", label: "Stat 2 — Valeur", field_type: "text", default_fr: "500+", default_en: "500+" },
    { slug: "stat_2_label", label: "Stat 2 — Label", field_type: "text", default_fr: "Catégories de produits", default_en: "Product categories" },
    { slug: "stat_3_value", label: "Stat 3 — Valeur", field_type: "text", default_fr: "AI", default_en: "AI" },
    { slug: "stat_3_label", label: "Stat 3 — Label", field_type: "text", default_fr: "Propulsé par Gemini", default_en: "Powered by Gemini" },
    { slug: "features_title", label: "Titre section features", field_type: "text", default_fr: "De la data brute aux opportunités actionnables", default_en: "From raw data to actionable opportunities" },
    { slug: "f1_title", label: "Feature 1 — Titre", field_type: "text", default_fr: "Carte mondiale des flux", default_en: "Global trade flow map" },
    { slug: "f1_desc", label: "Feature 1 — Description", field_type: "richtext", default_fr: "Visualisez les gaps d'import/export pays par pays. Identifiez où la demande dépasse l'offre locale.", default_en: "Visualise import/export gaps country by country. Identify where demand exceeds local supply." },
    { slug: "f2_title", label: "Feature 2 — Titre", field_type: "text", default_fr: "Opportunity Farming", default_en: "Opportunity Farming" },
    { slug: "f2_desc", label: "Feature 2 — Description", field_type: "richtext", default_fr: "Scannez votre produit. L'IA identifie les typologies de clients, les géographies et les canaux de distribution.", default_en: "Scan your product. AI identifies customer profiles, geographies and distribution channels." },
    { slug: "f3_title", label: "Feature 3 — Titre", field_type: "text", default_fr: "Business plans IA", default_en: "AI business plans" },
    { slug: "f3_desc", label: "Feature 3 — Description", field_type: "richtext", default_fr: "De l'idée au plan d'action. Capex, Opex, ROI, fournisseurs recommandés — tout généré par l'IA en quelques secondes.", default_en: "From idea to action plan. Capex, Opex, ROI, recommended suppliers — all generated by AI in seconds." },
    { slug: "f4_title", label: "Feature 4 — Titre", field_type: "text", default_fr: "Réseau d'influence", default_en: "Influencer network" },
    { slug: "f4_desc", label: "Feature 4 — Description", field_type: "richtext", default_fr: "Connectez vos produits à des influenceurs qualifiés. Liens affiliés trackés, paiements automatiques via Stripe.", default_en: "Connect your products to qualified influencers. Tracked affiliate links, automatic payouts via Stripe." },
    { slug: "cta_final_title", label: "CTA final — Titre", field_type: "text", default_fr: "Prêt à identifier votre prochain marché ?", default_en: "Ready to identify your next market?" },
    { slug: "cta_final_desc", label: "CTA final — Description", field_type: "text", default_fr: "Inscription gratuite. Aucune carte bancaire requise.", default_en: "Free registration. No credit card required." },
    { slug: "cta_final_btn", label: "CTA final — Bouton", field_type: "text", default_fr: "Créer mon compte →", default_en: "Create my account →" },
  ],
};

const ftgPricing: CollectionDef = {
  key: "pricing",
  label: "Page tarifs",
  slots: [
    { slug: "plan_explorer_name", label: "Explorer — Nom", field_type: "text", default_fr: "Explorer", default_en: "Explorer" },
    { slug: "plan_explorer_price", label: "Explorer — Prix", field_type: "text", default_fr: "Gratuit", default_en: "Free" },
    { slug: "plan_explorer_features", label: "Explorer — Features", field_type: "json", default_fr: '["Carte mondiale interactive","Scores d\'opportunité basiques","1 rapport pays gratuit / mois"]', default_en: '["Interactive world map","Basic opportunity scores","1 free country report / month"]' },
    { slug: "plan_data_name", label: "Data — Nom", field_type: "text", default_fr: "Data", default_en: "Data" },
    { slug: "plan_data_price", label: "Data — Prix", field_type: "text", default_fr: "29 €/mois", default_en: "€29/month" },
    { slug: "plan_data_features", label: "Data — Features", field_type: "json", default_fr: '["Recherches sauvegardées","Matérialisation des opportunités","Export CSV","Alertes email"]', default_en: '["Saved searches","Opportunity materialization","CSV export","Email alerts"]' },
    { slug: "plan_strategy_name", label: "Strategy — Nom", field_type: "text", default_fr: "Strategy", default_en: "Strategy" },
    { slug: "plan_strategy_price", label: "Strategy — Prix", field_type: "text", default_fr: "99 €/mois", default_en: "€99/month" },
    { slug: "plan_strategy_features", label: "Strategy — Features", field_type: "json", default_fr: '["Business plans IA","AI Trade Advisor","Farming scanner","Crédits IA inclus","Onboarding 1-on-1"]', default_en: '["AI business plans","AI Trade Advisor","Farming scanner","AI credits included","1-on-1 onboarding"]' },
    { slug: "plan_premium_name", label: "Premium — Nom", field_type: "text", default_fr: "Premium", default_en: "Premium" },
    { slug: "plan_premium_price", label: "Premium — Prix", field_type: "text", default_fr: "149 €/mois", default_en: "€149/month" },
    { slug: "plan_premium_features", label: "Premium — Features", field_type: "json", default_fr: '["Réseau influenceurs","Geo-matching","Dashboard affiliation","Sales map"]', default_en: '["Influencer network","Geo-matching","Affiliate dashboard","Sales map"]' },
  ],
};

const ftgAuth: CollectionDef = {
  key: "auth",
  label: "Authentification",
  slots: [
    { slug: "login_title", label: "Titre login", field_type: "text", default_fr: "Bon retour", default_en: "Welcome back" },
    { slug: "login_subtitle", label: "Sous-titre login", field_type: "text", default_fr: "Connectez-vous pour accéder à votre intelligence commerciale", default_en: "Sign in to access your trade intelligence" },
    { slug: "register_title", label: "Titre inscription", field_type: "text", default_fr: "Créez votre compte", default_en: "Create your account" },
    { slug: "register_subtitle", label: "Sous-titre inscription", field_type: "text", default_fr: "Commencez à explorer les opportunités mondiales gratuitement", default_en: "Start exploring global opportunities for free" },
  ],
};

const ftgMap: CollectionDef = {
  key: "map",
  label: "Carte interactive",
  slots: [
    { slug: "filter_label", label: "Label filtre", field_type: "text", default_fr: "Filtre", default_en: "Filter" },
    { slug: "countries_tracked", label: "Pays suivis", field_type: "text", default_fr: "pays suivis", default_en: "countries tracked" },
    { slug: "opportunities_label", label: "Opportunités", field_type: "text", default_fr: "opportunités identifiées", default_en: "identified opportunities" },
  ],
};

const ftgCountry: CollectionDef = {
  key: "country",
  label: "Fiche pays",
  slots: [
    { slug: "advisor_title", label: "Titre AI Advisor", field_type: "text", default_fr: "AI Trade Advisor", default_en: "AI Trade Advisor" },
    { slug: "advisor_desc", label: "Description Advisor", field_type: "richtext", default_fr: "Posez une question sur ce marché et recevez une analyse personnalisée.", default_en: "Ask a question about this market and get a personalized analysis." },
    { slug: "plan_title", label: "Titre Business Plan", field_type: "text", default_fr: "Business Plan IA", default_en: "AI Business Plan" },
  ],
};

const ftgReports: CollectionDef = {
  key: "reports",
  label: "Rapports",
  slots: [
    { slug: "page_title", label: "Titre page", field_type: "text", default_fr: "Rapports pays", default_en: "Country Reports" },
    { slug: "empty_state", label: "État vide", field_type: "text", default_fr: "Aucun rapport disponible. Explorez la carte pour générer des rapports.", default_en: "No reports available. Explore the map to generate reports." },
  ],
};

const ftgFarming: CollectionDef = {
  key: "farming",
  label: "Opportunity Farming",
  slots: [
    { slug: "page_title", label: "Titre page", field_type: "text", default_fr: "Opportunity Farming", default_en: "Opportunity Farming" },
    { slug: "scan_label", label: "Label scan", field_type: "text", default_fr: "Scanner un produit", default_en: "Scan a product" },
    { slug: "scan_desc", label: "Description scan", field_type: "richtext", default_fr: "Décrivez votre produit et l'IA identifie les marchés idéaux, les typologies de clients et les canaux de distribution.", default_en: "Describe your product and AI identifies ideal markets, customer profiles and distribution channels." },
  ],
};

const ftgInfluencer: CollectionDef = {
  key: "influencer",
  label: "Espace influenceur",
  slots: [
    { slug: "catalog_title", label: "Titre catalogue", field_type: "text", default_fr: "Catalogue produits", default_en: "Product Catalog" },
    { slug: "catalog_desc", label: "Description catalogue", field_type: "text", default_fr: "Parcourez les produits et générez vos liens affiliés.", default_en: "Browse products and generate your affiliate links." },
    { slug: "favorites_title", label: "Titre favoris", field_type: "text", default_fr: "Mes favoris", default_en: "My Favorites" },
    { slug: "dashboard_title", label: "Titre dashboard", field_type: "text", default_fr: "Dashboard Influenceur", default_en: "Influencer Dashboard" },
  ],
};

const ftgSeller: CollectionDef = {
  key: "seller",
  label: "Espace vendeur",
  slots: [
    { slug: "products_title", label: "Titre produits", field_type: "text", default_fr: "Mes produits", default_en: "My Products" },
    { slug: "products_desc", label: "Description", field_type: "text", default_fr: "Gérez vos produits et offres d'affiliation.", default_en: "Manage your products and affiliate offers." },
  ],
};

const ftgFunding: CollectionDef = {
  key: "funding",
  label: "Financement",
  slots: [
    { slug: "scenarios_title", label: "Titre scénarios", field_type: "text", default_fr: "Scénarios de financement", default_en: "Funding Scenarios" },
    { slug: "scenarios_desc", label: "Description", field_type: "richtext", default_fr: "Choisissez entre financement bancaire et investissement en equity.", default_en: "Choose between bank financing and equity investment." },
    { slug: "finance_title", label: "Titre espace financeur", field_type: "text", default_fr: "Espace Financeur", default_en: "Funder Space" },
    { slug: "invest_title", label: "Titre espace investisseur", field_type: "text", default_fr: "Espace Investisseur", default_en: "Investor Space" },
  ],
};

// ── Shift Dynamics ──────────────────────────────────────────────────────────

const shiftHome: CollectionDef = {
  key: "home",
  label: "Page d'accueil",
  slots: [
    { slug: "hero_badge", label: "Badge hero", field_type: "text", default_fr: "Conseil stratégique & technologique", default_en: "Strategic & Technology Consulting" },
    { slug: "hero_title", label: "Titre hero", field_type: "text", default_fr: "Transformez vos marchés", default_en: "Transform your markets" },
    { slug: "hero_subtitle", label: "Sous-titre hero", field_type: "richtext", default_fr: "22 ans d'expertise en deep tech, gaming et expansion internationale.", default_en: "22 years of expertise in deep tech, gaming and international expansion." },
    { slug: "stat_revenue", label: "Stat — Revenue", field_type: "text", default_fr: ">100M€", default_en: ">€100M" },
    { slug: "stat_countries", label: "Stat — Pays", field_type: "text", default_fr: "44", default_en: "44" },
    { slug: "stat_markets", label: "Stat — Marchés", field_type: "text", default_fr: "17", default_en: "17" },
  ],
};

const shiftAbout: CollectionDef = {
  key: "about",
  label: "Page À propos",
  slots: [
    { slug: "experience_years", label: "Années d'expérience", field_type: "number", default_fr: "22", default_en: "22" },
    { slug: "countries_covered", label: "Pays couverts", field_type: "number", default_fr: "44", default_en: "44" },
    { slug: "gaming_markets", label: "Marchés gaming", field_type: "number", default_fr: "17", default_en: "17" },
    { slug: "players_euro", label: "Players EURO 2016", field_type: "text", default_fr: "70K+", default_en: "70K+" },
    { slug: "quote", label: "Citation", field_type: "richtext", default_fr: "La technologie n'a de valeur que lorsqu'elle génère du revenu mesurable.", default_en: "Technology is only as valuable as the measurable revenue it generates." },
  ],
};

const shiftGaming: CollectionDef = {
  key: "gaming",
  label: "Vertical Gaming",
  slots: [
    { slug: "hero_title", label: "Titre hero", field_type: "text", default_fr: "Gaming & Esports", default_en: "Gaming & Esports" },
    { slug: "hero_desc", label: "Description", field_type: "richtext", default_fr: "Activation esports, gaming mobile, monetisation — 17 marchés africains couverts.", default_en: "Esports activation, mobile gaming, monetization — 17 African markets covered." },
    { slug: "cta", label: "CTA", field_type: "text", default_fr: "Réserver un audit stratégique", default_en: "Book a Strategic Audit" },
  ],
};

const shiftMarketEntry: CollectionDef = {
  key: "market_entry",
  label: "Vertical Market Entry",
  slots: [
    { slug: "hero_title", label: "Titre hero", field_type: "text", default_fr: "Expansion internationale", default_en: "International Expansion" },
    { slug: "hero_desc", label: "Description", field_type: "richtext", default_fr: "De l'étude de marché au premier client, nous structurons votre entrée.", default_en: "From market study to first client, we structure your entry." },
    { slug: "cta", label: "CTA", field_type: "text", default_fr: "Cartographier votre marché", default_en: "Map your market" },
  ],
};

const shiftDeepTech: CollectionDef = {
  key: "deep_tech",
  label: "Vertical Deep Tech",
  slots: [
    { slug: "hero_title", label: "Titre hero", field_type: "text", default_fr: "Deep Tech", default_en: "Deep Tech" },
    { slug: "hero_desc", label: "Description", field_type: "richtext", default_fr: "IA, blockchain, IoT — nous transformons l'innovation en revenus.", default_en: "AI, blockchain, IoT — we transform innovation into revenue." },
    { slug: "cta", label: "CTA", field_type: "text", default_fr: "Réserver un audit", default_en: "Book an Audit" },
  ],
};

const shiftAlliances: CollectionDef = {
  key: "alliances",
  label: "Vertical Alliances",
  slots: [
    { slug: "hero_title", label: "Titre hero", field_type: "text", default_fr: "Alliances Stratégiques", default_en: "Strategic Alliances" },
    { slug: "hero_desc", label: "Description", field_type: "richtext", default_fr: "Joint-ventures, partenariats, structuration d'alliances durables.", default_en: "Joint ventures, partnerships, structuring lasting alliances." },
    { slug: "cta", label: "CTA", field_type: "text", default_fr: "Structurer une alliance", default_en: "Structure an Alliance" },
  ],
};

const shiftBooking: CollectionDef = {
  key: "booking",
  label: "Booking",
  slots: [
    { slug: "page_title", label: "Titre", field_type: "text", default_fr: "Réserver une consultation", default_en: "Book a Consultation" },
    { slug: "page_desc", label: "Description", field_type: "richtext", default_fr: "Choisissez un créneau pour un appel stratégique de 30 ou 60 minutes.", default_en: "Choose a slot for a 30 or 60-minute strategic call." },
  ],
};

// ── The Estate ──────────────────────────────────────────────────────────────

const estateDashboard: CollectionDef = {
  key: "dashboard",
  label: "Dashboard",
  slots: [
    { slug: "services", label: "Services monitorés", field_type: "json", default_fr: '[{"name":"The Estate","icon":"🏨","color":"#C9A84C"},{"name":"Shift Dynamics","icon":"⚡","color":"#8B5CF6"},{"name":"Feel The Gap","icon":"🌍","color":"#3B82F6"},{"name":"Command Center","icon":"🎙️","color":"#10B981"}]', default_en: '[{"name":"The Estate","icon":"🏨","color":"#C9A84C"},{"name":"Shift Dynamics","icon":"⚡","color":"#8B5CF6"},{"name":"Feel The Gap","icon":"🌍","color":"#3B82F6"},{"name":"Command Center","icon":"🎙️","color":"#10B981"}]' },
    { slug: "tier_labels", label: "Labels des tiers", field_type: "json", default_fr: '{"explorer":"Explorer","data":"Data","strategy":"Strategy","premium":"Premium","enterprise":"Enterprise"}', default_en: '{"explorer":"Explorer","data":"Data","strategy":"Strategy","premium":"Premium","enterprise":"Enterprise"}' },
    { slug: "tier_colors", label: "Couleurs des tiers", field_type: "json", default_fr: '{"explorer":"#5A6A7A","data":"#3B82F6","strategy":"#8B5CF6","premium":"#C9A84C","enterprise":"#10B981"}', default_en: '{"explorer":"#5A6A7A","data":"#3B82F6","strategy":"#8B5CF6","premium":"#C9A84C","enterprise":"#10B981"}' },
  ],
};

const estateVoice: CollectionDef = {
  key: "voice",
  label: "Interface Aria",
  slots: [
    { slug: "welcome_text", label: "Texte d'accueil", field_type: "text", default_fr: "Maintenez l'orbe pour parler", default_en: "Hold the orb to speak" },
    { slug: "welcome_sub", label: "Sous-texte", field_type: "text", default_fr: "Relâchez pour envoyer", default_en: "Release to send" },
  ],
};

const estateLogin: CollectionDef = {
  key: "login",
  label: "Page login",
  slots: [
    { slug: "title", label: "Titre", field_type: "text", default_fr: "Accès restreint", default_en: "Restricted Access" },
    { slug: "subtitle", label: "Sous-titre", field_type: "text", default_fr: "Command Center · Espace administrateur", default_en: "Command Center · Admin Space" },
  ],
};

// ── Export ───────────────────────────────────────────────────────────────────

export const CMS_SITES: SiteDef[] = [
  { key: "ftg", label: "Feel The Gap", collections: [ftgLanding, ftgPricing, ftgAuth, ftgMap, ftgCountry, ftgReports, ftgFarming, ftgInfluencer, ftgSeller, ftgFunding] },
  { key: "shift", label: "Shift Dynamics", collections: [shiftHome, shiftAbout, shiftGaming, shiftMarketEntry, shiftDeepTech, shiftAlliances, shiftBooking] },
  { key: "estate", label: "The Estate", collections: [estateDashboard, estateVoice, estateLogin] },
];

/** Find a slot definition */
export function findSlot(siteKey: string, collectionKey: string, slug: string): SlotDef | undefined {
  const site = CMS_SITES.find((s) => s.key === siteKey);
  const coll = site?.collections.find((c) => c.key === collectionKey);
  return coll?.slots.find((s) => s.slug === slug);
}
