export type SourceType = 'free' | 'freemium' | 'paid'
export type SourceCategory = 'macro' | 'trade_flows' | 'agriculture' | 'energy' | 'consumer' | 'national_stats' | 'financial'

export interface DataSource {
  id: string
  name: string
  description: string
  type: SourceType
  category: SourceCategory
  coverage: string       // e.g. "190+ countries"
  update_frequency: string
  data_types: string[]
  api_url?: string
  docs_url?: string
  pricing_url?: string
  notes?: string
}

export const DATA_SOURCES: DataSource[] = [

  // ── FREE INTERNATIONAL ──────────────────────────────────────────────────────

  {
    id: 'world_bank',
    name: 'World Bank Open Data',
    description: 'Macro indicators: GDP, total imports/exports, population, arable land, infrastructure. Covers 190+ countries annually.',
    type: 'free',
    category: 'macro',
    coverage: '190+ pays',
    update_frequency: 'Annuel',
    data_types: ['GDP', 'Imports/Exports totaux', 'Population', 'Terres arables', 'Main d\'œuvre'],
    api_url: 'https://api.worldbank.org/v2',
    docs_url: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/889392',
  },
  {
    id: 'world_bank_wits',
    name: 'World Bank WITS',
    description: 'Bilateral trade flows par produit (codes HS). Données granulaires par partenaire commercial.',
    type: 'free',
    category: 'trade_flows',
    coverage: '180+ pays',
    update_frequency: 'Annuel',
    data_types: ['Flux bilatéraux HS6', 'Tarifs douaniers', 'Parts de marché'],
    api_url: 'https://wits.worldbank.org/API/V1',
    docs_url: 'https://wits.worldbank.org/WITS/WITS/AdvanceQuery/RawTradeData/QueryDefinition.aspx',
  },
  {
    id: 'wto_stats',
    name: 'WTO Statistics',
    description: 'Commerce de marchandises et services par pays membre. Tarifs, accords commerciaux, données d\'alerte.',
    type: 'free',
    category: 'trade_flows',
    coverage: '164 membres OMC',
    update_frequency: 'Trimestriel',
    data_types: ['Commerce marchandises', 'Commerce services', 'Tarifs MFN', 'Accords préférentiels'],
    api_url: 'https://api.wto.org/indicators/',
    docs_url: 'https://stats.wto.org/apidoc',
  },
  {
    id: 'imf_dots',
    name: 'IMF Direction of Trade Statistics',
    description: 'Flux bilatéraux imports/exports entre pays. Couverture complète des membres FMI.',
    type: 'free',
    category: 'macro',
    coverage: '190+ pays',
    update_frequency: 'Mensuel',
    data_types: ['Flux bilatéraux pays-à-pays', 'Balance commerciale', 'Partenaires principaux'],
    api_url: 'https://data.imf.org/api/',
    docs_url: 'https://data.imf.org/?sk=9D6028D4-F14A-464C-A2F2-59B2CD424B85',
  },
  {
    id: 'faostat',
    name: 'FAO STAT',
    description: 'Commerce agricole et alimentaire, production, sécurité alimentaire. Données sur 200+ produits par pays.',
    type: 'free',
    category: 'agriculture',
    coverage: '170+ pays',
    update_frequency: 'Annuel',
    data_types: ['Commerce agricole HS', 'Production alimentaire', 'Prix commodités agricoles', 'Sécurité alimentaire'],
    api_url: 'https://fenixservices.fao.org/faostat/api/v1',
    docs_url: 'https://www.fao.org/faostat/en/#data',
  },
  {
    id: 'eurostat',
    name: 'Eurostat COMEXT',
    description: 'Commerce intra et extra-UE détaillé (CN8, HS6). Source officielle EU Commission. Couverture 27 États membres + partenaires.',
    type: 'free',
    category: 'trade_flows',
    coverage: 'UE-27 + 200 partenaires',
    update_frequency: 'Mensuel',
    data_types: ['Flux HS6/CN8', 'Valeur et volume', 'Pays origine/destination', 'Nomenclature produits'],
    api_url: 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1',
    docs_url: 'https://ec.europa.eu/eurostat/web/international-trade-in-goods/data/database',
  },
  {
    id: 'usda_psd',
    name: 'USDA Production, Supply & Distribution',
    description: 'Données agricoles mondiales : production, consommation, stocks, commerce pour +40 commodités agricoles.',
    type: 'free',
    category: 'agriculture',
    coverage: '175+ pays',
    update_frequency: 'Mensuel',
    data_types: ['Céréales', 'Oléagineux', 'Coton', 'Sucre', 'Viande', 'Produits laitiers'],
    api_url: 'https://apps.fas.usda.gov/psdonline/api/psd',
    docs_url: 'https://apps.fas.usda.gov/psdonline/app/index.html#/app/downloads',
  },
  {
    id: 'un_comtrade_free',
    name: 'UN Comtrade (gratuit)',
    description: 'Base de données commerciale la plus complète au monde. Tier gratuit : 100 requêtes/heure, données HS6.',
    type: 'free',
    category: 'trade_flows',
    coverage: '200+ déclarants',
    update_frequency: 'Annuel',
    data_types: ['HS6 bilatéral', 'Valeur/Volume/Quantité', 'Mode transport', 'SITC'],
    api_url: 'https://comtradeapi.un.org/data/v1/get/',
    docs_url: 'https://comtradeplus.un.org/TradeFlow',
    notes: 'Nécessite une inscription gratuite sur comtradeplus.un.org',
  },
  {
    id: 'oecd_stat',
    name: 'OECD.Stat',
    description: 'Données économiques et commerciales des 37 pays membres OCDE. Forte couverture Europe, Amérique du Nord, Japon.',
    type: 'free',
    category: 'macro',
    coverage: '37 pays OCDE',
    update_frequency: 'Trimestriel',
    data_types: ['Balance paiements', 'Echanges biens/services', 'IDE', 'Indicateurs structurels'],
    api_url: 'https://stats.oecd.org/SDMX-JSON/data',
    docs_url: 'https://stats.oecd.org/',
  },
  {
    id: 'cia_factbook',
    name: 'CIA World Factbook',
    description: 'Profils pays structurés : top 10 imports/exports, partenaires principaux, contexte économique.',
    type: 'free',
    category: 'macro',
    coverage: '240 pays & territoires',
    update_frequency: 'Annuel',
    data_types: ['Top imports/exports', 'Partenaires commerciaux', 'Profil économique', 'Infrastructure'],
    api_url: 'https://github.com/factbook/factbook.json',
    docs_url: 'https://www.cia.gov/the-world-factbook/',
  },
  {
    id: 'owid',
    name: 'Our World in Data',
    description: 'Indicateurs socio-économiques, sécurité alimentaire, énergie. Données libres d\'accès et bien documentées.',
    type: 'free',
    category: 'macro',
    coverage: '200+ pays',
    update_frequency: 'Annuel',
    data_types: ['Énergie', 'Alimentation', 'Commerce', 'Développement'],
    api_url: 'https://ourworldindata.org/data',
    docs_url: 'https://github.com/owid/owid-datasets',
  },

  // ── STATISTIQUES NATIONALES (GRATUITES) ────────────────────────────────────

  {
    id: 'insee',
    name: 'INSEE (France)',
    description: 'Institut National de la Statistique. Commerce extérieur français détaillé, douanes, prix à la consommation.',
    type: 'free',
    category: 'national_stats',
    coverage: 'France',
    update_frequency: 'Mensuel',
    data_types: ['Commerce extérieur FR', 'Données douanières', 'Indices prix', 'Comptes nationaux'],
    api_url: 'https://api.insee.fr/series/BDM/V1',
    docs_url: 'https://www.insee.fr/fr/information/2868055',
    notes: 'Clé API gratuite disponible sur api.insee.fr',
  },
  {
    id: 'destatis',
    name: 'Destatis (Allemagne)',
    description: 'Statistisches Bundesamt. Commerce extérieur allemand, statistiques industrielles, prix.',
    type: 'free',
    category: 'national_stats',
    coverage: 'Allemagne',
    update_frequency: 'Mensuel',
    data_types: ['Commerce extérieur DE', 'Production industrielle', 'Indices prix', 'IPC'],
    docs_url: 'https://www.destatis.de/EN/Themes/Economy/Foreign-Trade/_node.html',
    api_url: 'https://www-genesis.destatis.de/genesisWS/rest/2020',
  },
  {
    id: 'ons',
    name: 'ONS (Royaume-Uni)',
    description: 'Office for National Statistics. Commerce UK post-Brexit, statistiques économiques.',
    type: 'free',
    category: 'national_stats',
    coverage: 'Royaume-Uni',
    update_frequency: 'Mensuel',
    data_types: ['Commerce extérieur UK', 'Balance paiements', 'PIB', 'Emploi'],
    api_url: 'https://api.beta.ons.gov.uk/v1',
    docs_url: 'https://www.ons.gov.uk/businessindustryandtrade/internationaltrade',
  },
  {
    id: 'istat',
    name: 'ISTAT (Italie)',
    description: 'Istituto Nazionale di Statistica. Commerce extérieur italien, production, prix.',
    type: 'free',
    category: 'national_stats',
    coverage: 'Italie',
    update_frequency: 'Mensuel',
    data_types: ['Commerce extérieur IT', 'Comptes nationaux', 'Production industrielle'],
    docs_url: 'https://www.istat.it/en/foreign-trade',
    api_url: 'https://sdmx.istat.it/SDMXWS/rest',
  },
  {
    id: 'ine_spain',
    name: 'INE (Espagne)',
    description: 'Instituto Nacional de Estadística. Commerce extérieur espagnol, Agence des Douanes Espagnoles (AEAT).',
    type: 'free',
    category: 'national_stats',
    coverage: 'Espagne',
    update_frequency: 'Mensuel',
    data_types: ['Commerce extérieur ES', 'IPC', 'PIB', 'Commerce intra-UE'],
    docs_url: 'https://www.ine.es/en/prensa/ep_prensa_en.htm',
    api_url: 'https://servicios.ine.es/wstempus/js',
  },
  {
    id: 'cbs_netherlands',
    name: 'CBS (Pays-Bas)',
    description: 'Statistics Netherlands. Commerce extérieur néerlandais, Rotterdam hub, données portuaires.',
    type: 'free',
    category: 'national_stats',
    coverage: 'Pays-Bas',
    update_frequency: 'Mensuel',
    data_types: ['Commerce extérieur NL', 'Données portuaires Rotterdam', 'Production industrielle'],
    api_url: 'https://opendata.cbs.nl/ODataApi/odata',
    docs_url: 'https://opendata.cbs.nl/statline/#/CBS/en/',
  },
  {
    id: 'stats_canada',
    name: 'Statistics Canada',
    description: 'Commerce extérieur canadien détaillé, ressources naturelles, agriculture.',
    type: 'free',
    category: 'national_stats',
    coverage: 'Canada',
    update_frequency: 'Mensuel',
    data_types: ['Commerce marchandises CA', 'Commerce services', 'Balance paiements'],
    api_url: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action',
    docs_url: 'https://www.statcan.gc.ca/en/subjects-start/international_trade',
  },
  {
    id: 'abs_australia',
    name: 'ABS (Australie)',
    description: 'Australian Bureau of Statistics. Commerce extérieur australien, ressources minérales, agro.',
    type: 'free',
    category: 'national_stats',
    coverage: 'Australie',
    update_frequency: 'Mensuel',
    data_types: ['Commerce marchandises AU', 'Balance paiements', 'Ressources minières'],
    api_url: 'https://api.data.abs.gov.au',
    docs_url: 'https://www.abs.gov.au/statistics/economy/international-trade',
  },
  {
    id: 'customs_china',
    name: 'Douanes Générales de Chine (GACC)',
    description: 'General Administration of Customs P.R. China. Commerce extérieur chinois, données mensuelles.',
    type: 'free',
    category: 'national_stats',
    coverage: 'Chine',
    update_frequency: 'Mensuel',
    data_types: ['Commerce extérieur CN', 'Importations HS', 'Partenaires commerciaux'],
    docs_url: 'http://www.customs.gov.cn/customs/302249/302274/302277/',
  },

  // ── ÉNERGIE ─────────────────────────────────────────────────────────────────

  {
    id: 'iea_stats',
    name: 'IEA Statistics',
    description: 'Agence Internationale de l\'Énergie. Imports/exports pétrole, gaz, électricité, charbon par pays.',
    type: 'free',
    category: 'energy',
    coverage: '150+ pays',
    update_frequency: 'Annuel',
    data_types: ['Pétrole brut & raffiné', 'Gaz naturel & GNL', 'Charbon', 'Électricité', 'Renouvelables'],
    api_url: 'https://api.iea.org/stats',
    docs_url: 'https://www.iea.org/data-and-statistics',
  },
  {
    id: 'eia',
    name: 'EIA (US Energy Information)',
    description: 'Données énergétiques mondiales, prix, production, commerce pétrolier et gazier.',
    type: 'free',
    category: 'energy',
    coverage: 'Mondial',
    update_frequency: 'Mensuel',
    data_types: ['Prix pétrole/gaz', 'Production mondiale', 'Flux LNG', 'Électricité'],
    api_url: 'https://api.eia.gov/v2',
    docs_url: 'https://www.eia.gov/opendata/',
    notes: 'Clé API gratuite sur eia.gov',
  },

  // ── PAYANTES ────────────────────────────────────────────────────────────────

  {
    id: 'un_comtrade_plus',
    name: 'UN Comtrade+',
    description: 'Accès illimité aux données HS-6 bilatérales. API REST, mises à jour temps réel, historique depuis 1962.',
    type: 'paid',
    category: 'trade_flows',
    coverage: '200+ déclarants',
    update_frequency: 'Mensuel',
    data_types: ['HS6 bilatéral illimité', 'Données en temps réel', 'Historique long terme', 'Mode transport'],
    pricing_url: 'https://comtradeplus.un.org/Subscription',
    docs_url: 'https://comtradeplus.un.org/',
    notes: 'À partir de $3 000/an',
  },
  {
    id: 'global_trade_atlas',
    name: 'Global Trade Atlas (Platts)',
    description: 'Base de données commerciale HS6 la plus complète. Données officielles douanières mensuelles pour +90 pays.',
    type: 'paid',
    category: 'trade_flows',
    coverage: '90+ pays en temps réel',
    update_frequency: 'Mensuel',
    data_types: ['HS6 données officielles', 'Statistiques mensuelles', 'Comparaisons historiques'],
    pricing_url: 'https://www.spglobal.com/commodityinsights/en/products-services/trade-data/global-trade-atlas',
    notes: 'À partir de $5 000/an',
  },
  {
    id: 'import_genius',
    name: 'Import Genius',
    description: 'Bill of lading data US, EU, Inde. Noms réels des importateurs/exportateurs, volumes, prix.',
    type: 'paid',
    category: 'trade_flows',
    coverage: 'USA, EU, Inde, Mexique',
    update_frequency: 'Hebdomadaire',
    data_types: ['Bills of lading', 'Noms importateurs/exportateurs', 'Volumes réels', 'Ports'],
    pricing_url: 'https://www.importgenius.com/pricing',
    notes: 'À partir de $99/mois — données douanières réelles',
  },
  {
    id: 'panjiva',
    name: 'Panjiva (S&P Global)',
    description: 'Bill of lading mondial, données de fret maritime, noms des acheteurs et vendeurs réels.',
    type: 'paid',
    category: 'trade_flows',
    coverage: 'Mondial (fret maritime)',
    update_frequency: 'Temps réel',
    data_types: ['Bills of lading', 'Acheteurs/vendeurs réels', 'Tonnage', 'Routes maritimes'],
    pricing_url: 'https://panjiva.com/pricing',
    notes: 'Niveau enterprise',
  },
  {
    id: 'gfk',
    name: 'GfK Consumer Intelligence',
    description: 'Panel consommateurs, données de ventes au détail, comportements d\'achat. Couverture Europe + Asie + Amériques.',
    type: 'paid',
    category: 'consumer',
    coverage: '60+ pays',
    update_frequency: 'Mensuel',
    data_types: ['Ventes détail par catégorie', 'Panel consommateurs', 'Prix marché', 'Tendances demande'],
    pricing_url: 'https://www.gfk.com/solutions/consumer-and-market-intelligence',
    notes: 'Prix sur devis',
  },
  {
    id: 'euromonitor',
    name: 'Euromonitor Passport',
    description: 'Données marché par catégorie, taille de marché, parts de marché, prévisions. Leader en market intelligence.',
    type: 'paid',
    category: 'consumer',
    coverage: '100+ pays',
    update_frequency: 'Annuel',
    data_types: ['Taille marchés', 'Parts de marché', 'Prévisions 5 ans', 'Profils distributeurs'],
    pricing_url: 'https://www.euromonitor.com/passport',
    notes: 'À partir de $15 000/an',
  },
  {
    id: 'oxford_economics',
    name: 'Oxford Economics',
    description: 'Prévisions macroéconomiques et commerciales. Modélisation commerce mondial, risques pays.',
    type: 'paid',
    category: 'financial',
    coverage: '200+ pays',
    update_frequency: 'Mensuel',
    data_types: ['Prévisions PIB/Commerce', 'Scénarios risques', 'Analyse sectorielle'],
    pricing_url: 'https://www.oxfordeconomics.com/',
    notes: 'Prix sur devis',
  },
]

export const SOURCES_BY_CATEGORY: Record<SourceCategory, DataSource[]> = {
  macro:          DATA_SOURCES.filter(s => s.category === 'macro'),
  trade_flows:    DATA_SOURCES.filter(s => s.category === 'trade_flows'),
  agriculture:    DATA_SOURCES.filter(s => s.category === 'agriculture'),
  energy:         DATA_SOURCES.filter(s => s.category === 'energy'),
  national_stats: DATA_SOURCES.filter(s => s.category === 'national_stats'),
  consumer:       DATA_SOURCES.filter(s => s.category === 'consumer'),
  financial:      DATA_SOURCES.filter(s => s.category === 'financial'),
}

export const CATEGORY_LABELS: Record<SourceCategory, { label: string; icon: string }> = {
  macro:          { label: 'Données macro',          icon: '🌍' },
  trade_flows:    { label: 'Flux commerciaux',        icon: '📦' },
  agriculture:    { label: 'Agriculture & alimentaire', icon: '🌾' },
  energy:         { label: 'Énergie',                icon: '⚡' },
  national_stats: { label: 'Statistiques nationales', icon: '🏛️' },
  consumer:       { label: 'Données consommateurs',  icon: '🛒' },
  financial:      { label: 'Finance & prévisions',   icon: '📊' },
}
