// Curated list of major B2B trade shows. Phase 0 MVP — 30 events.
// Expand to 200+ via Eventseye/10times scraping in future iterations.
//
// Data sources: official show websites (cross-checked Apr 2026).
// Dates are approximate (typical month/window) — update yearly.

export type TradeShow = {
  slug: string; // url-safe lowercase
  name: string;
  city: string;
  country: string; // ISO-2
  countryFlag: string; // emoji
  venue: string;
  startDate: string; // YYYY-MM-DD (typical)
  endDate: string;
  attendees: number; // approximate
  exhibitors: number; // approximate
  industry: string; // canonical category
  url: string; // official website
  description: string; // 1-2 sentences
};

export const TRADE_SHOWS: TradeShow[] = [
  {
    slug: "ifa-berlin-2026",
    name: "IFA Berlin 2026",
    city: "Berlin",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Berlin",
    startDate: "2026-09-04",
    endDate: "2026-09-08",
    attendees: 250000,
    exhibitors: 1900,
    industry: "Consumer Electronics",
    url: "https://www.ifa-berlin.com",
    description:
      "Salon mondial de l'électronique grand public et électroménager. Acheteurs B2B + presse + retailers globaux.",
  },
  {
    slug: "mwc-barcelona-2026",
    name: "Mobile World Congress Barcelona 2026",
    city: "Barcelona",
    country: "ES",
    countryFlag: "🇪🇸",
    venue: "Fira Gran Via",
    startDate: "2026-03-02",
    endDate: "2026-03-05",
    attendees: 95000,
    exhibitors: 2400,
    industry: "Mobile / Telecom",
    url: "https://www.mwcbarcelona.com",
    description:
      "Premier salon mondial de la mobilité, télécoms, 5G, IoT. Decision makers télécoms + opérateurs + équipementiers.",
  },
  {
    slug: "hannover-messe-2026",
    name: "Hannover Messe 2026",
    city: "Hannover",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Deutsche Messe",
    startDate: "2026-04-20",
    endDate: "2026-04-24",
    attendees: 130000,
    exhibitors: 4000,
    industry: "Industrial / Automation",
    url: "https://www.hannovermesse.de",
    description:
      "Plus grand salon industriel mondial. Industrie 4.0, robotique, énergie, automatisation. Importateurs équipement industriel.",
  },
  {
    slug: "imex-frankfurt-2026",
    name: "IMEX Frankfurt 2026",
    city: "Frankfurt",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Frankfurt",
    startDate: "2026-05-12",
    endDate: "2026-05-14",
    attendees: 14000,
    exhibitors: 4000,
    industry: "MICE / Business Travel",
    url: "https://www.imex-frankfurt.com",
    description:
      "Salon mondial du tourisme d'affaires, MICE, voyages B2B. Acheteurs corporate events + DMO + venues.",
  },
  {
    slug: "ces-las-vegas-2026",
    name: "CES Las Vegas 2026",
    city: "Las Vegas",
    country: "US",
    countryFlag: "🇺🇸",
    venue: "Las Vegas Convention Center",
    startDate: "2026-01-06",
    endDate: "2026-01-09",
    attendees: 138000,
    exhibitors: 4500,
    industry: "Consumer Electronics",
    url: "https://www.ces.tech",
    description:
      "Le plus grand salon tech au monde. Lancement produits, AI, mobilité, smart home. Distributeurs + importateurs internationaux.",
  },
  {
    slug: "iaa-munich-2026",
    name: "IAA Mobility Munich 2026",
    city: "Munich",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe München",
    startDate: "2026-09-08",
    endDate: "2026-09-13",
    attendees: 500000,
    exhibitors: 750,
    industry: "Automotive",
    url: "https://www.iaa.de",
    description:
      "Salon automobile premium d'Europe. Constructeurs + suppliers + EV + mobilité urbaine. Importateurs automobile + équipement.",
  },
  {
    slug: "ispo-munich-2026",
    name: "ISPO Munich 2026",
    city: "Munich",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe München",
    startDate: "2026-01-25",
    endDate: "2026-01-28",
    attendees: 80000,
    exhibitors: 2700,
    industry: "Sports / Outdoor",
    url: "https://www.ispo.com",
    description:
      "Premier salon sport & outdoor B2B. Marques + distributeurs + retailers sportif. Importateurs équipement.",
  },
  {
    slug: "fruit-logistica-berlin-2026",
    name: "Fruit Logistica Berlin 2026",
    city: "Berlin",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Berlin",
    startDate: "2026-02-04",
    endDate: "2026-02-06",
    attendees: 75000,
    exhibitors: 2700,
    industry: "Fresh Produce / Agri",
    url: "https://www.fruitlogistica.com",
    description:
      "Salon mondial fruits & légumes frais. Importateurs + grossistes + retailers. Trade flows produits frais EU + global.",
  },
  {
    slug: "ambiente-frankfurt-2026",
    name: "Ambiente Frankfurt 2026",
    city: "Frankfurt",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Frankfurt",
    startDate: "2026-02-13",
    endDate: "2026-02-17",
    attendees: 120000,
    exhibitors: 4500,
    industry: "Consumer Goods",
    url: "https://ambiente.messefrankfurt.com",
    description:
      "Plus grand salon biens consommation : table, cuisine, design, gifts. Acheteurs retail + e-com mondiaux.",
  },
  {
    slug: "salon-auto-paris-2026",
    name: "Mondial de l'Auto Paris 2026",
    city: "Paris",
    country: "FR",
    countryFlag: "🇫🇷",
    venue: "Paris Expo Porte de Versailles",
    startDate: "2026-10-06",
    endDate: "2026-10-12",
    attendees: 800000,
    exhibitors: 250,
    industry: "Automotive",
    url: "https://www.mondial-paris.com",
    description:
      "Salon automobile français de référence. Constructeurs + suppliers + EV. Distributeurs + importateurs auto Europe + Maghreb + Afrique.",
  },
  {
    slug: "vivatech-paris-2026",
    name: "VivaTech Paris 2026",
    city: "Paris",
    country: "FR",
    countryFlag: "🇫🇷",
    venue: "Paris Expo Porte de Versailles",
    startDate: "2026-06-11",
    endDate: "2026-06-13",
    attendees: 165000,
    exhibitors: 13000,
    industry: "Tech / Startup",
    url: "https://vivatechnology.com",
    description:
      "Plus grand salon tech & startup d'Europe. AI, deeptech, climate tech, mobility. Investisseurs + corporates + scale-ups.",
  },
  {
    slug: "slush-helsinki-2026",
    name: "Slush Helsinki 2026",
    city: "Helsinki",
    country: "FI",
    countryFlag: "🇫🇮",
    venue: "Messukeskus",
    startDate: "2026-11-19",
    endDate: "2026-11-20",
    attendees: 13000,
    exhibitors: 4500,
    industry: "Tech / VC",
    url: "https://slush.org",
    description:
      "Salon nordique startups + VCs. Tech founders, deeptech, climate, scale-ups Series A-C. International deals.",
  },
  {
    slug: "web-summit-lisbon-2026",
    name: "Web Summit Lisbon 2026",
    city: "Lisbon",
    country: "PT",
    countryFlag: "🇵🇹",
    venue: "Altice Arena",
    startDate: "2026-11-09",
    endDate: "2026-11-12",
    attendees: 71000,
    exhibitors: 2600,
    industry: "Tech / Conference",
    url: "https://websummit.com",
    description:
      "Premier salon tech mondial. Founders + corporates + investors + media. Distribution mondiale, deals cross-border.",
  },
  {
    slug: "anuga-cologne-2026",
    name: "Anuga Cologne 2026",
    city: "Cologne",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Koelnmesse",
    startDate: "2026-10-10",
    endDate: "2026-10-14",
    attendees: 170000,
    exhibitors: 8000,
    industry: "Food & Beverage",
    url: "https://www.anuga.com",
    description:
      "Plus grand salon food B2B mondial. Importateurs + retail + foodservice + distribution. Référence trade flows alimentaire global.",
  },
  {
    slug: "prowein-dusseldorf-2026",
    name: "ProWein Düsseldorf 2026",
    city: "Düsseldorf",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf",
    startDate: "2026-03-15",
    endDate: "2026-03-17",
    attendees: 49000,
    exhibitors: 5700,
    industry: "Wines & Spirits",
    url: "https://www.prowein.com",
    description:
      "Salon mondial vins & spiritueux B2B. Importateurs + distributeurs + retail. Trade flows vins France/Italie/Espagne global.",
  },
  {
    slug: "logimat-stuttgart-2026",
    name: "LogiMAT Stuttgart 2026",
    city: "Stuttgart",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Stuttgart",
    startDate: "2026-03-10",
    endDate: "2026-03-12",
    attendees: 65000,
    exhibitors: 1700,
    industry: "Logistics / Intralogistics",
    url: "https://www.logimat-messe.de",
    description:
      "Salon européen logistique intralogistique : warehouses, robots, supply chain. Acheteurs B2B logistique + e-com.",
  },
  {
    slug: "transport-logistic-munich-2026",
    name: "transport logistic Munich 2026",
    city: "Munich",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe München",
    startDate: "2026-05-04",
    endDate: "2026-05-07",
    attendees: 75000,
    exhibitors: 2300,
    industry: "Transport / Logistics",
    url: "https://www.transportlogistic.de",
    description:
      "Premier salon mondial transport et logistique. Freight, maritime, air cargo, road, rail. Forwarders + shippers internationaux.",
  },
  {
    slug: "cosmoprof-bologna-2026",
    name: "Cosmoprof Bologna 2026",
    city: "Bologna",
    country: "IT",
    countryFlag: "🇮🇹",
    venue: "BolognaFiere",
    startDate: "2026-03-19",
    endDate: "2026-03-23",
    attendees: 250000,
    exhibitors: 3000,
    industry: "Beauty / Cosmetics",
    url: "https://www.cosmoprof.com",
    description:
      "Premier salon mondial beauté/cosmétique B2B. Marques + distributeurs + retailers. Importateurs cosmétique global.",
  },
  {
    slug: "ids-cologne-2026",
    name: "IDS Cologne 2026 (Dental)",
    city: "Cologne",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Koelnmesse",
    startDate: "2026-03-10",
    endDate: "2026-03-14",
    attendees: 120000,
    exhibitors: 2000,
    industry: "Dental",
    url: "https://www.english.ids-cologne.de",
    description:
      "Salon mondial dentaire B2B. Équipement + consommables + tech dentaire. Distributeurs + cabinets dentaires + cliniques.",
  },
  {
    slug: "medica-dusseldorf-2026",
    name: "MEDICA Düsseldorf 2026",
    city: "Düsseldorf",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf",
    startDate: "2026-11-16",
    endDate: "2026-11-19",
    attendees: 80000,
    exhibitors: 5300,
    industry: "Medical Devices",
    url: "https://www.medica.de",
    description:
      "Plus grand salon médical mondial. Dispositifs médicaux + healthcare + lab. Importateurs équipement médical global.",
  },
  {
    slug: "arab-health-dubai-2026",
    name: "Arab Health Dubai 2026",
    city: "Dubai",
    country: "AE",
    countryFlag: "🇦🇪",
    venue: "Dubai World Trade Centre",
    startDate: "2026-01-26",
    endDate: "2026-01-29",
    attendees: 110000,
    exhibitors: 3500,
    industry: "Medical / Healthcare",
    url: "https://www.arabhealthonline.com",
    description:
      "Premier salon médical Moyen-Orient + Asie. Acheteurs cliniques + distributeurs MENA + Asie centrale + Afrique.",
  },
  {
    slug: "sial-paris-2026",
    name: "SIAL Paris 2026",
    city: "Paris",
    country: "FR",
    countryFlag: "🇫🇷",
    venue: "Paris-Nord Villepinte",
    startDate: "2026-10-17",
    endDate: "2026-10-21",
    attendees: 265000,
    exhibitors: 7500,
    industry: "Food & Beverage",
    url: "https://www.sialparis.com",
    description:
      "Premier salon agroalimentaire mondial. Producteurs + importateurs + retailers + foodservice. Trade flows alimentaire France/EU/global.",
  },
  {
    slug: "fhc-shanghai-2026",
    name: "FHC Shanghai 2026",
    city: "Shanghai",
    country: "CN",
    countryFlag: "🇨🇳",
    venue: "SNIEC",
    startDate: "2026-11-09",
    endDate: "2026-11-11",
    attendees: 140000,
    exhibitors: 3500,
    industry: "Food & Hospitality",
    url: "https://www.fhcchina.com",
    description:
      "Premier salon food + hospitality Chine. Importateurs Asie pour foods occidentaux + matériel hospitality.",
  },
  {
    slug: "canton-fair-guangzhou-2026",
    name: "Canton Fair Guangzhou 2026 (Spring)",
    city: "Guangzhou",
    country: "CN",
    countryFlag: "🇨🇳",
    venue: "Canton Fair Complex",
    startDate: "2026-04-15",
    endDate: "2026-05-05",
    attendees: 600000,
    exhibitors: 28000,
    industry: "General Manufacturing",
    url: "https://www.cantonfair.org.cn/en",
    description:
      "Plus grand salon import-export Chine. Manufacturing + electronics + textile + machinery. Acheteurs internationaux par milliers.",
  },
  {
    slug: "automechanika-frankfurt-2026",
    name: "Automechanika Frankfurt 2026",
    city: "Frankfurt",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Frankfurt",
    startDate: "2026-09-15",
    endDate: "2026-09-19",
    attendees: 80000,
    exhibitors: 4500,
    industry: "Automotive Aftermarket",
    url: "https://automechanika.messefrankfurt.com",
    description:
      "Premier salon mondial pièces auto + aftermarket + service auto. Distributeurs + ateliers + équipementiers.",
  },
  {
    slug: "drupa-dusseldorf-2026",
    name: "drupa Düsseldorf 2026",
    city: "Düsseldorf",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf",
    startDate: "2026-05-28",
    endDate: "2026-06-07",
    attendees: 175000,
    exhibitors: 1600,
    industry: "Print / Packaging",
    url: "https://www.drupa.com",
    description:
      "Salon mondial print + packaging. Imprimerie industrielle, packaging, équipement. Distributeurs international + B2B emballage.",
  },
  {
    slug: "interpack-dusseldorf-2026",
    name: "interpack Düsseldorf 2026",
    city: "Düsseldorf",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf",
    startDate: "2026-05-07",
    endDate: "2026-05-13",
    attendees: 170000,
    exhibitors: 2700,
    industry: "Packaging / Process",
    url: "https://www.interpack.com",
    description:
      "Salon mondial process & packaging tous secteurs. Food, pharma, cosmetics, industrial. Acheteurs équipement industriel global.",
  },
  {
    slug: "itb-berlin-2026",
    name: "ITB Berlin 2026",
    city: "Berlin",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Berlin",
    startDate: "2026-03-04",
    endDate: "2026-03-08",
    attendees: 100000,
    exhibitors: 5500,
    industry: "Travel / Tourism",
    url: "https://www.itb-berlin.com",
    description:
      "Plus grand salon tourisme mondial B2B. Operators + DMO + airlines + hotels. Acheteurs tour-operators internationaux.",
  },
  {
    slug: "techtextil-frankfurt-2026",
    name: "Techtextil Frankfurt 2026",
    city: "Frankfurt",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Frankfurt",
    startDate: "2026-04-21",
    endDate: "2026-04-24",
    attendees: 47000,
    exhibitors: 1700,
    industry: "Technical Textiles",
    url: "https://techtextil.messefrankfurt.com",
    description:
      "Premier salon textiles techniques mondial. Geo-textiles, medical textiles, automotive, smart textiles. B2B industriel.",
  },
  {
    slug: "salon-agriculture-paris-2026",
    name: "Salon International Agriculture Paris 2026",
    city: "Paris",
    country: "FR",
    countryFlag: "🇫🇷",
    venue: "Paris Expo Porte de Versailles",
    startDate: "2026-02-21",
    endDate: "2026-03-01",
    attendees: 600000,
    exhibitors: 1000,
    industry: "Agriculture / Food",
    url: "https://www.salon-agriculture.com",
    description:
      "Plus grand salon agriculture France. Producteurs + équipement agri + élevage. Distribution alimentaire France + export.",
  },
];

export function bySlug(slug: string): TradeShow | undefined {
  return TRADE_SHOWS.find((s) => s.slug === slug);
}

export function upcoming(): TradeShow[] {
  const now = new Date().toISOString().split("T")[0];
  return TRADE_SHOWS.filter((s) => s.startDate >= now).sort((a, b) =>
    a.startDate.localeCompare(b.startDate),
  );
}
