// Curated list of major B2B trade shows. 100 events (30 MVP + 70 wave-2 expansion).
// Expand to 200+ via Eventseye/10times scraping in future iterations.
//
// Data sources: official show websites (cross-checked Apr 2026).
// Dates are approximate (typical month/window) — update yearly.

export type TradeShow = {
  slug: string; // url-safe lowercase
  name: string;
  city: string;
  country: string; // ISO-2
  countryFlag: string; // emoji
  venue: string;
  startDate: string; // YYYY-MM-DD (typical)
  endDate: string;
  attendees: number; // approximate
  exhibitors: number; // approximate
  industry: string; // canonical category
  url: string; // official website
  description: string; // 1-2 sentences
};

export const TRADE_SHOWS: TradeShow[] = [
  {
    slug: "ifa-berlin-2026",
    name: "IFA Berlin 2026",
    city: "Berlin",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Berlin",
    startDate: "2026-09-04",
    endDate: "2026-09-08",
    attendees: 250000,
    exhibitors: 1900,
    industry: "Consumer Electronics",
    url: "https://www.ifa-berlin.com",
    description:
      "Salon mondial de l'électronique grand public et électroménager. Acheteurs B2B + presse + retailers globaux.",
  },
  {
    slug: "mwc-barcelona-2026",
    name: "Mobile World Congress Barcelona 2026",
    city: "Barcelona",
    country: "ES",
    countryFlag: "🇪🇸",
    venue: "Fira Gran Via",
    startDate: "2026-03-02",
    endDate: "2026-03-05",
    attendees: 95000,
    exhibitors: 2400,
    industry: "Mobile / Telecom",
    url: "https://www.mwcbarcelona.com",
    description:
      "Premier salon mondial de la mobilité, télécoms, 5G, IoT. Decision makers télécoms + opérateurs + équipementiers.",
  },
  {
    slug: "hannover-messe-2026",
    name: "Hannover Messe 2026",
    city: "Hannover",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Deutsche Messe",
    startDate: "2026-04-20",
    endDate: "2026-04-24",
    attendees: 130000,
    exhibitors: 4000,
    industry: "Industrial / Automation",
    url: "https://www.hannovermesse.de",
    description:
      "Plus grand salon industriel mondial. Industrie 4.0, robotique, énergie, automatisation. Importateurs équipement industriel.",
  },
  {
    slug: "imex-frankfurt-2026",
    name: "IMEX Frankfurt 2026",
    city: "Frankfurt",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Frankfurt",
    startDate: "2026-05-12",
    endDate: "2026-05-14",
    attendees: 14000,
    exhibitors: 4000,
    industry: "MICE / Business Travel",
    url: "https://www.imex-frankfurt.com",
    description:
      "Salon mondial du tourisme d'affaires, MICE, voyages B2B. Acheteurs corporate events + DMO + venues.",
  },
  {
    slug: "ces-las-vegas-2026",
    name: "CES Las Vegas 2026",
    city: "Las Vegas",
    country: "US",
    countryFlag: "🇺🇸",
    venue: "Las Vegas Convention Center",
    startDate: "2026-01-06",
    endDate: "2026-01-09",
    attendees: 138000,
    exhibitors: 4500,
    industry: "Consumer Electronics",
    url: "https://www.ces.tech",
    description:
      "Le plus grand salon tech au monde. Lancement produits, AI, mobilité, smart home. Distributeurs + importateurs internationaux.",
  },
  {
    slug: "iaa-munich-2026",
    name: "IAA Mobility Munich 2026",
    city: "Munich",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe München",
    startDate: "2026-09-08",
    endDate: "2026-09-13",
    attendees: 500000,
    exhibitors: 750,
    industry: "Automotive",
    url: "https://www.iaa.de",
    description:
      "Salon automobile premium d'Europe. Constructeurs + suppliers + EV + mobilité urbaine. Importateurs automobile + équipement.",
  },
  {
    slug: "ispo-munich-2026",
    name: "ISPO Munich 2026",
    city: "Munich",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe München",
    startDate: "2026-01-25",
    endDate: "2026-01-28",
    attendees: 80000,
    exhibitors: 2700,
    industry: "Sports / Outdoor",
    url: "https://www.ispo.com",
    description:
      "Premier salon sport & outdoor B2B. Marques + distributeurs + retailers sportif. Importateurs équipement.",
  },
  {
    slug: "fruit-logistica-berlin-2026",
    name: "Fruit Logistica Berlin 2026",
    city: "Berlin",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Berlin",
    startDate: "2026-02-04",
    endDate: "2026-02-06",
    attendees: 75000,
    exhibitors: 2700,
    industry: "Fresh Produce / Agri",
    url: "https://www.fruitlogistica.com",
    description:
      "Salon mondial fruits & légumes frais. Importateurs + grossistes + retailers. Trade flows produits frais EU + global.",
  },
  {
    slug: "ambiente-frankfurt-2026",
    name: "Ambiente Frankfurt 2026",
    city: "Frankfurt",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Frankfurt",
    startDate: "2026-02-13",
    endDate: "2026-02-17",
    attendees: 120000,
    exhibitors: 4500,
    industry: "Consumer Goods",
    url: "https://ambiente.messefrankfurt.com",
    description:
      "Plus grand salon biens consommation : table, cuisine, design, gifts. Acheteurs retail + e-com mondiaux.",
  },
  {
    slug: "salon-auto-paris-2026",
    name: "Mondial de l'Auto Paris 2026",
    city: "Paris",
    country: "FR",
    countryFlag: "🇫🇷",
    venue: "Paris Expo Porte de Versailles",
    startDate: "2026-10-06",
    endDate: "2026-10-12",
    attendees: 800000,
    exhibitors: 250,
    industry: "Automotive",
    url: "https://www.mondial-paris.com",
    description:
      "Salon automobile français de référence. Constructeurs + suppliers + EV. Distributeurs + importateurs auto Europe + Maghreb + Afrique.",
  },
  {
    slug: "vivatech-paris-2026",
    name: "VivaTech Paris 2026",
    city: "Paris",
    country: "FR",
    countryFlag: "🇫🇷",
    venue: "Paris Expo Porte de Versailles",
    startDate: "2026-06-11",
    endDate: "2026-06-13",
    attendees: 165000,
    exhibitors: 13000,
    industry: "Tech / Startup",
    url: "https://vivatechnology.com",
    description:
      "Plus grand salon tech & startup d'Europe. AI, deeptech, climate tech, mobility. Investisseurs + corporates + scale-ups.",
  },
  {
    slug: "slush-helsinki-2026",
    name: "Slush Helsinki 2026",
    city: "Helsinki",
    country: "FI",
    countryFlag: "🇫🇮",
    venue: "Messukeskus",
    startDate: "2026-11-19",
    endDate: "2026-11-20",
    attendees: 13000,
    exhibitors: 4500,
    industry: "Tech / VC",
    url: "https://slush.org",
    description:
      "Salon nordique startups + VCs. Tech founders, deeptech, climate, scale-ups Series A-C. International deals.",
  },
  {
    slug: "web-summit-lisbon-2026",
    name: "Web Summit Lisbon 2026",
    city: "Lisbon",
    country: "PT",
    countryFlag: "🇵🇹",
    venue: "Altice Arena",
    startDate: "2026-11-09",
    endDate: "2026-11-12",
    attendees: 71000,
    exhibitors: 2600,
    industry: "Tech / Conference",
    url: "https://websummit.com",
    description:
      "Premier salon tech mondial. Founders + corporates + investors + media. Distribution mondiale, deals cross-border.",
  },
  {
    slug: "anuga-cologne-2026",
    name: "Anuga Cologne 2026",
    city: "Cologne",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Koelnmesse",
    startDate: "2026-10-10",
    endDate: "2026-10-14",
    attendees: 170000,
    exhibitors: 8000,
    industry: "Food & Beverage",
    url: "https://www.anuga.com",
    description:
      "Plus grand salon food B2B mondial. Importateurs + retail + foodservice + distribution. Référence trade flows alimentaire global.",
  },
  {
    slug: "prowein-dusseldorf-2026",
    name: "ProWein Düsseldorf 2026",
    city: "Düsseldorf",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf",
    startDate: "2026-03-15",
    endDate: "2026-03-17",
    attendees: 49000,
    exhibitors: 5700,
    industry: "Wines & Spirits",
    url: "https://www.prowein.com",
    description:
      "Salon mondial vins & spiritueux B2B. Importateurs + distributeurs + retail. Trade flows vins France/Italie/Espagne global.",
  },
  {
    slug: "logimat-stuttgart-2026",
    name: "LogiMAT Stuttgart 2026",
    city: "Stuttgart",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Stuttgart",
    startDate: "2026-03-10",
    endDate: "2026-03-12",
    attendees: 65000,
    exhibitors: 1700,
    industry: "Logistics / Intralogistics",
    url: "https://www.logimat-messe.de",
    description:
      "Salon européen logistique intralogistique : warehouses, robots, supply chain. Acheteurs B2B logistique + e-com.",
  },
  {
    slug: "transport-logistic-munich-2026",
    name: "transport logistic Munich 2026",
    city: "Munich",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe München",
    startDate: "2026-05-04",
    endDate: "2026-05-07",
    attendees: 75000,
    exhibitors: 2300,
    industry: "Transport / Logistics",
    url: "https://www.transportlogistic.de",
    description:
      "Premier salon mondial transport et logistique. Freight, maritime, air cargo, road, rail. Forwarders + shippers internationaux.",
  },
  {
    slug: "cosmoprof-bologna-2026",
    name: "Cosmoprof Bologna 2026",
    city: "Bologna",
    country: "IT",
    countryFlag: "🇮🇹",
    venue: "BolognaFiere",
    startDate: "2026-03-19",
    endDate: "2026-03-23",
    attendees: 250000,
    exhibitors: 3000,
    industry: "Beauty / Cosmetics",
    url: "https://www.cosmoprof.com",
    description:
      "Premier salon mondial beauté/cosmétique B2B. Marques + distributeurs + retailers. Importateurs cosmétique global.",
  },
  {
    slug: "ids-cologne-2026",
    name: "IDS Cologne 2026 (Dental)",
    city: "Cologne",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Koelnmesse",
    startDate: "2026-03-10",
    endDate: "2026-03-14",
    attendees: 120000,
    exhibitors: 2000,
    industry: "Dental",
    url: "https://www.english.ids-cologne.de",
    description:
      "Salon mondial dentaire B2B. Équipement + consommables + tech dentaire. Distributeurs + cabinets dentaires + cliniques.",
  },
  {
    slug: "medica-dusseldorf-2026",
    name: "MEDICA Düsseldorf 2026",
    city: "Düsseldorf",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf",
    startDate: "2026-11-16",
    endDate: "2026-11-19",
    attendees: 80000,
    exhibitors: 5300,
    industry: "Medical Devices",
    url: "https://www.medica.de",
    description:
      "Plus grand salon médical mondial. Dispositifs médicaux + healthcare + lab. Importateurs équipement médical global.",
  },
  {
    slug: "arab-health-dubai-2026",
    name: "Arab Health Dubai 2026",
    city: "Dubai",
    country: "AE",
    countryFlag: "🇦🇪",
    venue: "Dubai World Trade Centre",
    startDate: "2026-01-26",
    endDate: "2026-01-29",
    attendees: 110000,
    exhibitors: 3500,
    industry: "Medical / Healthcare",
    url: "https://www.arabhealthonline.com",
    description:
      "Premier salon médical Moyen-Orient + Asie. Acheteurs cliniques + distributeurs MENA + Asie centrale + Afrique.",
  },
  {
    slug: "sial-paris-2026",
    name: "SIAL Paris 2026",
    city: "Paris",
    country: "FR",
    countryFlag: "🇫🇷",
    venue: "Paris-Nord Villepinte",
    startDate: "2026-10-17",
    endDate: "2026-10-21",
    attendees: 265000,
    exhibitors: 7500,
    industry: "Food & Beverage",
    url: "https://www.sialparis.com",
    description:
      "Premier salon agroalimentaire mondial. Producteurs + importateurs + retailers + foodservice. Trade flows alimentaire France/EU/global.",
  },
  {
    slug: "fhc-shanghai-2026",
    name: "FHC Shanghai 2026",
    city: "Shanghai",
    country: "CN",
    countryFlag: "🇨🇳",
    venue: "SNIEC",
    startDate: "2026-11-09",
    endDate: "2026-11-11",
    attendees: 140000,
    exhibitors: 3500,
    industry: "Food & Hospitality",
    url: "https://www.fhcchina.com",
    description:
      "Premier salon food + hospitality Chine. Importateurs Asie pour foods occidentaux + matériel hospitality.",
  },
  {
    slug: "canton-fair-guangzhou-2026",
    name: "Canton Fair Guangzhou 2026 (Spring)",
    city: "Guangzhou",
    country: "CN",
    countryFlag: "🇨🇳",
    venue: "Canton Fair Complex",
    startDate: "2026-04-15",
    endDate: "2026-05-05",
    attendees: 600000,
    exhibitors: 28000,
    industry: "General Manufacturing",
    url: "https://www.cantonfair.org.cn/en",
    description:
      "Plus grand salon import-export Chine. Manufacturing + electronics + textile + machinery. Acheteurs internationaux par milliers.",
  },
  {
    slug: "automechanika-frankfurt-2026",
    name: "Automechanika Frankfurt 2026",
    city: "Frankfurt",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Frankfurt",
    startDate: "2026-09-15",
    endDate: "2026-09-19",
    attendees: 80000,
    exhibitors: 4500,
    industry: "Automotive Aftermarket",
    url: "https://automechanika.messefrankfurt.com",
    description:
      "Premier salon mondial pièces auto + aftermarket + service auto. Distributeurs + ateliers + équipementiers.",
  },
  {
    slug: "drupa-dusseldorf-2026",
    name: "drupa Düsseldorf 2026",
    city: "Düsseldorf",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf",
    startDate: "2026-05-28",
    endDate: "2026-06-07",
    attendees: 175000,
    exhibitors: 1600,
    industry: "Print / Packaging",
    url: "https://www.drupa.com",
    description:
      "Salon mondial print + packaging. Imprimerie industrielle, packaging, équipement. Distributeurs international + B2B emballage.",
  },
  {
    slug: "interpack-dusseldorf-2026",
    name: "interpack Düsseldorf 2026",
    city: "Düsseldorf",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf",
    startDate: "2026-05-07",
    endDate: "2026-05-13",
    attendees: 170000,
    exhibitors: 2700,
    industry: "Packaging / Process",
    url: "https://www.interpack.com",
    description:
      "Salon mondial process & packaging tous secteurs. Food, pharma, cosmetics, industrial. Acheteurs équipement industriel global.",
  },
  {
    slug: "itb-berlin-2026",
    name: "ITB Berlin 2026",
    city: "Berlin",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Berlin",
    startDate: "2026-03-04",
    endDate: "2026-03-08",
    attendees: 100000,
    exhibitors: 5500,
    industry: "Travel / Tourism",
    url: "https://www.itb-berlin.com",
    description:
      "Plus grand salon tourisme mondial B2B. Operators + DMO + airlines + hotels. Acheteurs tour-operators internationaux.",
  },
  {
    slug: "techtextil-frankfurt-2026",
    name: "Techtextil Frankfurt 2026",
    city: "Frankfurt",
    country: "DE",
    countryFlag: "🇩🇪",
    venue: "Messe Frankfurt",
    startDate: "2026-04-21",
    endDate: "2026-04-24",
    attendees: 47000,
    exhibitors: 1700,
    industry: "Technical Textiles",
    url: "https://techtextil.messefrankfurt.com",
    description:
      "Premier salon textiles techniques mondial. Geo-textiles, medical textiles, automotive, smart textiles. B2B industriel.",
  },
  {
    slug: "salon-agriculture-paris-2026",
    name: "Salon International Agriculture Paris 2026",
    city: "Paris",
    country: "FR",
    countryFlag: "🇫🇷",
    venue: "Paris Expo Porte de Versailles",
    startDate: "2026-02-21",
    endDate: "2026-03-01",
    attendees: 600000,
    exhibitors: 1000,
    industry: "Agriculture / Food",
    url: "https://www.salon-agriculture.com",
    description:
      "Plus grand salon agriculture France. Producteurs + équipement agri + élevage. Distribution alimentaire France + export.",
  },
  // ── Wave-2 expansion (70 additional curated B2B shows) ─────────────────
  {
    slug: "fruit-logistica-berlin-2026", name: "Fruit Logistica Berlin 2026", city: "Berlin", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Berlin", startDate: "2026-02-04", endDate: "2026-02-06", attendees: 65000, exhibitors: 2700,
    industry: "Agriculture / Fresh produce", url: "https://www.fruitlogistica.com",
    description: "Salon mondial fruits et légumes frais. Producteurs + importateurs + retailers. Marché €50B+ annuel.",
  },
  {
    slug: "anuga-cologne-2026", name: "Anuga Cologne 2026", city: "Cologne", country: "DE", countryFlag: "🇩🇪",
    venue: "Koelnmesse", startDate: "2026-10-10", endDate: "2026-10-14", attendees: 170000, exhibitors: 7500,
    industry: "Food & Beverage", url: "https://www.anuga.com",
    description: "Plus grand salon F&B au monde. Importateurs + distributeurs alimentaires + producteurs 100+ pays.",
  },
  {
    slug: "sial-paris-2026", name: "SIAL Paris 2026", city: "Paris", country: "FR", countryFlag: "🇫🇷",
    venue: "Paris Nord Villepinte", startDate: "2026-10-17", endDate: "2026-10-21", attendees: 285000, exhibitors: 7200,
    industry: "Food Innovation", url: "https://www.sialparis.com",
    description: "Salon innovation alimentaire #1 mondial. Acheteurs hyper-spécialisés + R&D food + emballage.",
  },
  {
    slug: "interpack-dusseldorf-2026", name: "Interpack Düsseldorf 2026", city: "Düsseldorf", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf", startDate: "2026-05-07", endDate: "2026-05-13", attendees: 175000, exhibitors: 2700,
    industry: "Packaging / Processing", url: "https://www.interpack.com",
    description: "Salon mondial emballage + processing food/pharma/cosmétique. Acheteurs industriels globaux.",
  },
  {
    slug: "cphi-worldwide-2026", name: "CPHI Worldwide 2026", city: "Madrid", country: "ES", countryFlag: "🇪🇸",
    venue: "IFEMA Madrid", startDate: "2026-10-13", endDate: "2026-10-15", attendees: 60000, exhibitors: 2500,
    industry: "Pharmaceutical", url: "https://www.cphi.com",
    description: "Salon mondial pharmaceutique. APIs + finished dosage + outsourcing + machinery. Marché €1.4T.",
  },
  {
    slug: "drupa-dusseldorf-2026", name: "drupa Düsseldorf 2026", city: "Düsseldorf", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf", startDate: "2026-05-28", endDate: "2026-06-07", attendees: 280000, exhibitors: 1800,
    industry: "Print / Packaging Tech", url: "https://www.drupa.com",
    description: "Salon mondial print + packaging technology. Imprimeries + emballage + signage globaux.",
  },
  {
    slug: "jec-world-paris-2026", name: "JEC World Composites Paris 2026", city: "Paris", country: "FR", countryFlag: "🇫🇷",
    venue: "Paris Nord Villepinte", startDate: "2026-04-29", endDate: "2026-05-01", attendees: 40000, exhibitors: 1300,
    industry: "Composites Materials", url: "https://www.jec-world.events",
    description: "Salon mondial composites. Aéronautique + automotive + énergie. Sourcing matériaux avancés.",
  },
  {
    slug: "vitafoods-europe-2026", name: "Vitafoods Europe Geneva 2026", city: "Geneva", country: "CH", countryFlag: "🇨🇭",
    venue: "Palexpo", startDate: "2026-05-12", endDate: "2026-05-14", attendees: 25000, exhibitors: 1300,
    industry: "Nutraceuticals", url: "https://www.vitafoods.eu.com",
    description: "Salon ingrédients nutraceutiques + compléments. Sourcing R&D santé + bien-être globaux.",
  },
  {
    slug: "hannover-messe-2026", name: "Hannover Messe 2026", city: "Hannover", country: "DE", countryFlag: "🇩🇪",
    venue: "Hannover Fairground", startDate: "2026-04-13", endDate: "2026-04-17", attendees: 130000, exhibitors: 4000,
    industry: "Industry 4.0 / Manufacturing", url: "https://www.hannovermesse.de",
    description: "Salon mondial industrie. Automation + énergie + R&D + digital factory. ICP industriel global.",
  },
  {
    slug: "automechanika-frankfurt-2026", name: "Automechanika Frankfurt 2026", city: "Frankfurt", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Frankfurt", startDate: "2026-09-08", endDate: "2026-09-12", attendees: 130000, exhibitors: 4900,
    industry: "Automotive Aftermarket", url: "https://automechanika.messefrankfurt.com",
    description: "Salon mondial pièces auto + équipement atelier. Importateurs + distributeurs aftermarket globaux.",
  },
  {
    slug: "intermat-paris-2026", name: "Intermat Paris 2026", city: "Paris", country: "FR", countryFlag: "🇫🇷",
    venue: "Paris Nord Villepinte", startDate: "2026-04-20", endDate: "2026-04-25", attendees: 200000, exhibitors: 1500,
    industry: "Construction Equipment", url: "https://paris.intermatconstruction.com",
    description: "Salon mondial équipement construction + matériel BTP. Sourcing engins + outils + machinerie.",
  },
  {
    slug: "bauma-munich-2026", name: "bauma Munich 2026", city: "Munich", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe München", startDate: "2026-04-06", endDate: "2026-04-12", attendees: 600000, exhibitors: 3700,
    industry: "Construction Machinery", url: "https://www.bauma.de",
    description: "Plus grand salon construction au monde. Engins de chantier + matériaux + équipement minier.",
  },
  {
    slug: "ces-las-vegas-2027", name: "CES Las Vegas 2027", city: "Las Vegas", country: "US", countryFlag: "🇺🇸",
    venue: "Las Vegas Convention Center", startDate: "2027-01-06", endDate: "2027-01-09", attendees: 135000, exhibitors: 4500,
    industry: "Consumer Electronics / Tech", url: "https://www.ces.tech",
    description: "Salon high-tech #1 mondial. Lancement produits B2C/B2B globaux. Acheteurs distrib internationaux.",
  },
  {
    slug: "iaa-mobility-munich-2027", name: "IAA Mobility Munich 2027", city: "Munich", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe München", startDate: "2027-09-07", endDate: "2027-09-12", attendees: 500000, exhibitors: 750,
    industry: "Automotive / Mobility", url: "https://www.iaa.de",
    description: "Salon mobilité mondial. Constructeurs + équipementiers + mobility tech + durabilité.",
  },
  {
    slug: "premiere-vision-paris-2026", name: "Première Vision Paris 2026", city: "Paris", country: "FR", countryFlag: "🇫🇷",
    venue: "Paris Nord Villepinte", startDate: "2026-09-23", endDate: "2026-09-25", attendees: 60000, exhibitors: 1800,
    industry: "Textiles / Fashion", url: "https://www.premierevision.com",
    description: "Salon mondial textiles + tissus haut de gamme. Designers + acheteurs mode + retailers luxe.",
  },
  {
    slug: "magic-las-vegas-2026", name: "MAGIC Las Vegas 2026", city: "Las Vegas", country: "US", countryFlag: "🇺🇸",
    venue: "Las Vegas Convention Center", startDate: "2026-08-09", endDate: "2026-08-12", attendees: 70000, exhibitors: 2900,
    industry: "Apparel / Fashion", url: "https://www.magicfashionevents.com",
    description: "Plus grand salon B2B mode aux US. Marques + retailers + sourcing apparel + accessoires globaux.",
  },
  {
    slug: "canton-fair-spring-2026", name: "Canton Fair Spring 2026", city: "Guangzhou", country: "CN", countryFlag: "🇨🇳",
    venue: "Canton Fair Complex", startDate: "2026-04-15", endDate: "2026-05-05", attendees: 200000, exhibitors: 25000,
    industry: "Trade Multi-sector", url: "https://www.cantonfair.org.cn",
    description: "Plus grande foire commerce Chine. Sourcing toutes industries depuis manufacturing chinois.",
  },
  {
    slug: "imex-frankfurt-2026", name: "IMEX Frankfurt 2026", city: "Frankfurt", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Frankfurt", startDate: "2026-05-19", endDate: "2026-05-21", attendees: 14000, exhibitors: 3500,
    industry: "MICE / Events", url: "https://www.imex-frankfurt.com",
    description: "Salon mondial MICE (meetings, incentives, conferences, events). Hôtels + DMC + tech events.",
  },
  {
    slug: "bio-international-2026", name: "BIO International Convention 2026", city: "Boston", country: "US", countryFlag: "🇺🇸",
    venue: "Boston Convention Center", startDate: "2026-06-15", endDate: "2026-06-18", attendees: 19000, exhibitors: 1800,
    industry: "Biotechnology", url: "https://convention.bio.org",
    description: "Salon biotech #1 mondial. Pharma + academia + investisseurs + licensing IP biotech.",
  },
  {
    slug: "mipim-cannes-2026", name: "MIPIM Cannes 2026", city: "Cannes", country: "FR", countryFlag: "🇫🇷",
    venue: "Palais des Festivals", startDate: "2026-03-10", endDate: "2026-03-13", attendees: 27000, exhibitors: 350,
    industry: "Real Estate", url: "https://www.mipim.com",
    description: "Salon immobilier international. Investisseurs + développeurs + foncières + cities globaux.",
  },
  {
    slug: "expo-real-munich-2026", name: "Expo Real Munich 2026", city: "Munich", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe München", startDate: "2026-10-06", endDate: "2026-10-08", attendees: 41000, exhibitors: 1900,
    industry: "Real Estate Europe", url: "https://exporeal.net",
    description: "Salon immobilier européen #1. Investisseurs institutionnels + asset managers + développeurs EU.",
  },
  {
    slug: "ispo-munich-2026", name: "ISPO Munich 2026", city: "Munich", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe München", startDate: "2026-12-01", endDate: "2026-12-03", attendees: 80000, exhibitors: 2700,
    industry: "Sports / Outdoor", url: "https://www.ispo.com",
    description: "Salon mondial sport + outdoor. Marques sport + équipement + retailers internationaux.",
  },
  {
    slug: "viv-europe-utrecht-2026", name: "VIV Europe Utrecht 2026", city: "Utrecht", country: "NL", countryFlag: "🇳🇱",
    venue: "Jaarbeurs Utrecht", startDate: "2026-06-09", endDate: "2026-06-11", attendees: 25000, exhibitors: 600,
    industry: "Animal Husbandry", url: "https://www.viveurope.nl",
    description: "Salon élevage industriel mondial. Aviculture + porc + équipement + nutrition animale.",
  },
  {
    slug: "world-of-coffee-amsterdam-2026", name: "World of Coffee Amsterdam 2026", city: "Amsterdam", country: "NL", countryFlag: "🇳🇱",
    venue: "RAI Amsterdam", startDate: "2026-06-25", endDate: "2026-06-27", attendees: 12000, exhibitors: 250,
    industry: "Coffee / Specialty", url: "https://worldofcoffee.org",
    description: "Salon café spécialité mondial. Importateurs + roasters + équipement + producteurs origines.",
  },
  {
    slug: "prowein-dusseldorf-2026", name: "ProWein Düsseldorf 2026", city: "Düsseldorf", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf", startDate: "2026-03-15", endDate: "2026-03-17", attendees: 50000, exhibitors: 5800,
    industry: "Wine / Spirits", url: "https://www.prowein.com",
    description: "Salon vins + spiritueux #1 mondial. Producteurs + importateurs + sommeliers + retailers globaux.",
  },
  {
    slug: "vinexpo-paris-2026", name: "Vinexpo Paris 2026", city: "Paris", country: "FR", countryFlag: "🇫🇷",
    venue: "Paris Expo", startDate: "2026-02-10", endDate: "2026-02-12", attendees: 35000, exhibitors: 2900,
    industry: "Wine / Beverages", url: "https://www.vinexposium.com",
    description: "Salon vin internationale Paris. Producteurs France + Italie + Espagne + Nouveau Monde + Chine acheteurs.",
  },
  {
    slug: "ambiente-frankfurt-2026", name: "Ambiente Frankfurt 2026", city: "Frankfurt", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Frankfurt", startDate: "2026-02-06", endDate: "2026-02-10", attendees: 130000, exhibitors: 4400,
    industry: "Consumer Goods", url: "https://ambiente.messefrankfurt.com",
    description: "Plus grand salon biens consommation au monde. Tableware + interior + giving. Retailers internationaux.",
  },
  {
    slug: "gulfood-dubai-2026", name: "Gulfood Dubai 2026", city: "Dubai", country: "AE", countryFlag: "🇦🇪",
    venue: "Dubai World Trade Centre", startDate: "2026-02-16", endDate: "2026-02-20", attendees: 110000, exhibitors: 5500,
    industry: "Food / MENA", url: "https://www.gulfood.com",
    description: "Plus grand salon F&B Moyen-Orient + Afrique. Importateurs MENA pour producteurs européens/asiatiques.",
  },
  {
    slug: "art-basel-2026", name: "Art Basel 2026", city: "Basel", country: "CH", countryFlag: "🇨🇭",
    venue: "Messe Basel", startDate: "2026-06-18", endDate: "2026-06-21", attendees: 92000, exhibitors: 290,
    industry: "Art / Luxury", url: "https://www.artbasel.com",
    description: "Foire art contemporain #1 mondial. Collectionneurs + galeries + investisseurs art globaux.",
  },
  {
    slug: "smm-hamburg-2026", name: "SMM Hamburg 2026", city: "Hamburg", country: "DE", countryFlag: "🇩🇪",
    venue: "Hamburg Messe", startDate: "2026-09-08", endDate: "2026-09-11", attendees: 50000, exhibitors: 2200,
    industry: "Maritime / Shipping", url: "https://www.smm-hamburg.com",
    description: "Salon maritime international. Construction navale + équipement + shipping + offshore.",
  },
  {
    slug: "windenergy-hamburg-2026", name: "WindEnergy Hamburg 2026", city: "Hamburg", country: "DE", countryFlag: "🇩🇪",
    venue: "Hamburg Messe", startDate: "2026-09-22", endDate: "2026-09-25", attendees: 35000, exhibitors: 1400,
    industry: "Renewable Energy", url: "https://www.windenergyhamburg.com",
    description: "Salon mondial éolien. Turbines + offshore + storage + grid. Sourcing supply chain renewable.",
  },
  {
    slug: "intersolar-munich-2026", name: "Intersolar Munich 2026", city: "Munich", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe München", startDate: "2026-06-17", endDate: "2026-06-19", attendees: 100000, exhibitors: 2200,
    industry: "Solar / Renewable", url: "https://www.intersolar.de",
    description: "Plus grand salon solaire au monde. Modules + onduleurs + storage + EPC. Sourcing global photovoltaïque.",
  },
  {
    slug: "in-cosmetics-paris-2026", name: "in-cosmetics Paris 2026", city: "Paris", country: "FR", countryFlag: "🇫🇷",
    venue: "Paris Porte de Versailles", startDate: "2026-04-21", endDate: "2026-04-23", attendees: 11000, exhibitors: 800,
    industry: "Cosmetics / Personal Care", url: "https://www.in-cosmetics.com",
    description: "Salon ingrédients cosmétique #1 monde. R&D + formulation + sourcing actifs naturels + synthétiques.",
  },
  {
    slug: "cosmoprof-bologna-2026", name: "Cosmoprof Bologna 2026", city: "Bologna", country: "IT", countryFlag: "🇮🇹",
    venue: "BolognaFiere", startDate: "2026-03-19", endDate: "2026-03-22", attendees: 250000, exhibitors: 2900,
    industry: "Beauty / Cosmetics", url: "https://www.cosmoprof.com",
    description: "Plus grand salon beauté mondial. Marques + retailers + spas + B2B beauté globaux.",
  },
  {
    slug: "world-travel-market-london-2026", name: "World Travel Market London 2026", city: "London", country: "GB", countryFlag: "🇬🇧",
    venue: "ExCeL London", startDate: "2026-11-02", endDate: "2026-11-04", attendees: 50000, exhibitors: 5000,
    industry: "Travel / Tourism", url: "https://www.wtm.com",
    description: "Salon tourisme international #1 UK. Tour-opérateurs + hôtels + DMC + destinations.",
  },
  {
    slug: "fitur-madrid-2026", name: "FITUR Madrid 2026", city: "Madrid", country: "ES", countryFlag: "🇪🇸",
    venue: "IFEMA Madrid", startDate: "2026-01-21", endDate: "2026-01-25", attendees: 250000, exhibitors: 9000,
    industry: "Tourism / Travel", url: "https://www.ifema.es/fitur",
    description: "Plus grand salon tourisme Europe + Amérique latine. Destinations + tour-opérateurs + hôtels.",
  },
  {
    slug: "embedded-world-nuremberg-2026", name: "Embedded World Nuremberg 2026", city: "Nuremberg", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Nürnberg", startDate: "2026-03-10", endDate: "2026-03-12", attendees: 35000, exhibitors: 1100,
    industry: "Electronics / Embedded", url: "https://www.embedded-world.de",
    description: "Salon électronique embarquée mondial. IoT + automotive + medical electronics + industrial.",
  },
  {
    slug: "ifa-global-markets-2026", name: "IFA Global Markets 2026", city: "Berlin", country: "DE", countryFlag: "🇩🇪",
    venue: "Station Berlin", startDate: "2026-09-04", endDate: "2026-09-08", attendees: 8000, exhibitors: 700,
    industry: "Electronics Sourcing", url: "https://www.ifa-berlin.com",
    description: "B2B sourcing électronique consumer. Distributeurs européens cherchent fabricants asiatiques.",
  },
  {
    slug: "national-restaurant-show-chicago-2026", name: "National Restaurant Show Chicago 2026", city: "Chicago", country: "US", countryFlag: "🇺🇸",
    venue: "McCormick Place", startDate: "2026-05-16", endDate: "2026-05-19", attendees: 55000, exhibitors: 2300,
    industry: "Restaurant / Foodservice", url: "https://www.nationalrestaurantshow.com",
    description: "Plus grand salon restaurant US. Équipement + ingrédients + tech foodservice + chains.",
  },
  {
    slug: "k-show-dusseldorf-2026", name: "K Show Düsseldorf 2026", city: "Düsseldorf", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Düsseldorf", startDate: "2026-10-08", endDate: "2026-10-15", attendees: 200000, exhibitors: 3300,
    industry: "Plastics / Rubber", url: "https://www.k-online.com",
    description: "Salon plastiques + caoutchouc #1 mondial (triennal). Machinerie + matières premières + recyclage.",
  },
  {
    slug: "logimat-stuttgart-2026", name: "LogiMAT Stuttgart 2026", city: "Stuttgart", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Stuttgart", startDate: "2026-03-31", endDate: "2026-04-02", attendees: 65000, exhibitors: 1700,
    industry: "Logistics / Intralogistics", url: "https://www.logimat-messe.de",
    description: "Salon logistique intralogistique Europe. Automation entrepôt + warehouse tech + transport.",
  },
  {
    slug: "bigbuyer-bologna-2026", name: "Big Buyer Bologna 2026", city: "Bologna", country: "IT", countryFlag: "🇮🇹",
    venue: "BolognaFiere", startDate: "2026-11-19", endDate: "2026-11-21", attendees: 12000, exhibitors: 350,
    industry: "Stationery / Office", url: "https://www.bigbuyer.it",
    description: "Salon stationery + bureau Italie. Acheteurs grande distribution + chains spécialisées.",
  },
  {
    slug: "spielwarenmesse-nuremberg-2026", name: "Spielwarenmesse Nuremberg 2026", city: "Nuremberg", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Nürnberg", startDate: "2026-01-28", endDate: "2026-02-01", attendees: 65000, exhibitors: 2700,
    industry: "Toys / Games", url: "https://www.spielwarenmesse.de",
    description: "Salon jouets #1 mondial. Marques + distributeurs + retailers globaux. Lancements produits.",
  },
  {
    slug: "european-seafood-expo-barcelona-2026", name: "European Seafood Expo Barcelona 2026", city: "Barcelona", country: "ES", countryFlag: "🇪🇸",
    venue: "Fira Gran Via", startDate: "2026-04-21", endDate: "2026-04-23", attendees: 30000, exhibitors: 1800,
    industry: "Seafood / Aquaculture", url: "https://www.seafoodexpo.com",
    description: "Plus grand salon seafood Europe. Producteurs + importateurs + retailers + foodservice.",
  },
  {
    slug: "iftm-top-resa-paris-2026", name: "IFTM Top Resa Paris 2026", city: "Paris", country: "FR", countryFlag: "🇫🇷",
    venue: "Paris Porte de Versailles", startDate: "2026-09-22", endDate: "2026-09-24", attendees: 32000, exhibitors: 1500,
    industry: "Travel B2B France", url: "https://www.iftm.fr",
    description: "Salon B2B tourisme + voyage France. Tour-opérateurs + DMC + transport + hôtels.",
  },
  {
    slug: "nse-las-vegas-2026", name: "NACS Show Las Vegas 2026", city: "Las Vegas", country: "US", countryFlag: "🇺🇸",
    venue: "Las Vegas Convention Center", startDate: "2026-10-04", endDate: "2026-10-07", attendees: 25000, exhibitors: 1200,
    industry: "Convenience / Retail", url: "https://www.nacsshow.com",
    description: "Salon convenience stores US. Acheteurs gas station + small chains + foodservice on-the-go.",
  },
  {
    slug: "natural-products-expo-west-2026", name: "Natural Products Expo West 2026", city: "Anaheim", country: "US", countryFlag: "🇺🇸",
    venue: "Anaheim Convention Center", startDate: "2026-03-10", endDate: "2026-03-14", attendees: 89000, exhibitors: 3000,
    industry: "Natural / Organic Foods", url: "https://www.expowest.com",
    description: "Plus grand salon naturel/bio US. Marques + retailers + foodservice. Tendances clean label.",
  },
  {
    slug: "biofach-nuremberg-2026", name: "BioFach Nuremberg 2026", city: "Nuremberg", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Nürnberg", startDate: "2026-02-10", endDate: "2026-02-13", attendees: 40000, exhibitors: 2700,
    industry: "Organic Foods", url: "https://www.biofach.de",
    description: "Salon bio mondial #1. Producteurs + importateurs + retailers organic + R&D innovation.",
  },
  {
    slug: "outdoor-retailer-salt-lake-2026", name: "Outdoor Retailer Salt Lake 2026", city: "Salt Lake City", country: "US", countryFlag: "🇺🇸",
    venue: "Salt Palace", startDate: "2026-06-16", endDate: "2026-06-18", attendees: 20000, exhibitors: 1000,
    industry: "Outdoor / Sports US", url: "https://www.outdoorretailer.com",
    description: "Salon outdoor B2B US. Marques + retailers + buyers grand outdoor + camping + hiking.",
  },
  {
    slug: "shanghai-cosmoprof-2026", name: "Cosmoprof Asia Hong Kong 2026", city: "Hong Kong", country: "HK", countryFlag: "🇭🇰",
    venue: "AsiaWorld-Expo", startDate: "2026-11-11", endDate: "2026-11-13", attendees: 90000, exhibitors: 3500,
    industry: "Beauty Asia", url: "https://www.cosmoprof-asia.com",
    description: "Plus grand salon beauté Asie. Marques + retailers + sourcing ingrédients/packaging APAC.",
  },
  {
    slug: "asia-fruit-logistica-hk-2026", name: "Asia Fruit Logistica HK 2026", city: "Hong Kong", country: "HK", countryFlag: "🇭🇰",
    venue: "AsiaWorld-Expo", startDate: "2026-09-02", endDate: "2026-09-04", attendees: 14000, exhibitors: 850,
    industry: "Fresh Produce Asia", url: "https://www.asiafruitlogistica.com",
    description: "Salon fruits/légumes Asie. Importateurs Chine + Asie SE + Inde pour producteurs globaux.",
  },
  {
    slug: "bett-london-2026", name: "Bett London 2026", city: "London", country: "GB", countryFlag: "🇬🇧",
    venue: "ExCeL London", startDate: "2026-01-21", endDate: "2026-01-23", attendees: 35000, exhibitors: 600,
    industry: "EdTech", url: "https://www.bettshow.com",
    description: "Salon edtech #1 mondial. Solutions + équipement + curriculum + administrateurs éducation.",
  },
  {
    slug: "world-trade-summit-mar-2026", name: "World Trade Summit Marrakech 2026", city: "Marrakech", country: "MA", countryFlag: "🇲🇦",
    venue: "Palais des Congrès", startDate: "2026-11-15", endDate: "2026-11-17", attendees: 8000, exhibitors: 200,
    industry: "Trade / Africa", url: "https://www.worldtradesummit.org",
    description: "Sommet commerce Afrique. Importateurs/exportateurs Maghreb + Afrique de l'Ouest + Europe du Sud.",
  },
  {
    slug: "agritechnica-hannover-2026", name: "Agritechnica Hannover 2026", city: "Hannover", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Hannover", startDate: "2026-11-08", endDate: "2026-11-14", attendees: 470000, exhibitors: 2800,
    industry: "Agriculture Equipment", url: "https://www.agritechnica.com",
    description: "Plus grand salon machines agricoles au monde. Tracteurs + outils + précision agriculture + digital farming.",
  },
  {
    slug: "eima-bologna-2026", name: "EIMA Bologna 2026", city: "Bologna", country: "IT", countryFlag: "🇮🇹",
    venue: "BolognaFiere", startDate: "2026-11-04", endDate: "2026-11-08", attendees: 320000, exhibitors: 1900,
    industry: "Agricultural Machinery", url: "https://www.eima.it",
    description: "Salon machines agricoles + jardinage Italie. Acheteurs européens + Afrique pour fabricants italiens.",
  },
  {
    slug: "expopack-mexico-2026", name: "ExpoPack Mexico 2026", city: "Mexico City", country: "MX", countryFlag: "🇲🇽",
    venue: "Citibanamex Center", startDate: "2026-06-09", endDate: "2026-06-12", attendees: 30000, exhibitors: 1000,
    industry: "Packaging Latin America", url: "https://www.expopack.com.mx",
    description: "Salon packaging Amérique latine. Acheteurs Mexique + Amérique centrale pour fournisseurs globaux.",
  },
  {
    slug: "pack-expo-las-vegas-2027", name: "PACK EXPO Las Vegas 2027", city: "Las Vegas", country: "US", countryFlag: "🇺🇸",
    venue: "Las Vegas Convention Center", startDate: "2027-09-27", endDate: "2027-09-30", attendees: 32000, exhibitors: 2200,
    industry: "Packaging US", url: "https://www.packexpolasvegas.com",
    description: "Plus grand salon packaging Amérique du Nord. Industries food/pharma/cosmétique/CPG.",
  },
  {
    slug: "tokyo-game-show-2026", name: "Tokyo Game Show 2026", city: "Tokyo", country: "JP", countryFlag: "🇯🇵",
    venue: "Makuhari Messe", startDate: "2026-09-24", endDate: "2026-09-27", attendees: 240000, exhibitors: 600,
    industry: "Gaming / Entertainment", url: "https://tgs.cesa.or.jp",
    description: "Plus grand salon gaming Asie. Studios + publishers + IP licensing + esports + B2B Asia gaming.",
  },
  {
    slug: "gamescom-cologne-2026", name: "Gamescom Cologne 2026", city: "Cologne", country: "DE", countryFlag: "🇩🇪",
    venue: "Koelnmesse", startDate: "2026-08-26", endDate: "2026-08-30", attendees: 320000, exhibitors: 1100,
    industry: "Video Games / Gaming", url: "https://www.gamescom.global",
    description: "Plus grand salon gaming au monde. Studios + publishers + retailers + esports + tech gaming.",
  },
  {
    slug: "labelexpo-europe-2027", name: "Labelexpo Europe 2027", city: "Brussels", country: "BE", countryFlag: "🇧🇪",
    venue: "Brussels Expo", startDate: "2027-09-21", endDate: "2027-09-24", attendees: 30000, exhibitors: 600,
    industry: "Label / Packaging Print", url: "https://www.labelexpo-europe.com",
    description: "Salon étiquettes + packaging printing Europe. Imprimeries + matériaux + machinerie label.",
  },
  {
    slug: "iaapa-orlando-2026", name: "IAAPA Expo Orlando 2026", city: "Orlando", country: "US", countryFlag: "🇺🇸",
    venue: "Orange County Convention Center", startDate: "2026-11-16", endDate: "2026-11-19", attendees: 41000, exhibitors: 1100,
    industry: "Attractions / Theme Parks", url: "https://www.iaapa.org/expos/iaapa-expo",
    description: "Plus grand salon attractions parks au monde. Manèges + jeux + restauration thématique + tech parks.",
  },
  {
    slug: "ifsec-london-2026", name: "IFSEC London 2026", city: "London", country: "GB", countryFlag: "🇬🇧",
    venue: "ExCeL London", startDate: "2026-05-19", endDate: "2026-05-21", attendees: 27000, exhibitors: 350,
    industry: "Security / Surveillance", url: "https://www.ifsecglobal.com",
    description: "Salon sécurité + surveillance Europe. Vidéo surveillance + access control + cyber + intégrateurs.",
  },
  {
    slug: "isc-west-las-vegas-2026", name: "ISC West Las Vegas 2026", city: "Las Vegas", country: "US", countryFlag: "🇺🇸",
    venue: "Venetian Expo", startDate: "2026-04-08", endDate: "2026-04-10", attendees: 27000, exhibitors: 1000,
    industry: "Security US", url: "https://www.iscwest.com",
    description: "Plus grand salon sécurité US. Vidéosurveillance + cyber + intégrateurs + government.",
  },
  {
    slug: "americasmart-atlanta-2026", name: "AmericasMart Atlanta Gift Show 2026", city: "Atlanta", country: "US", countryFlag: "🇺🇸",
    venue: "AmericasMart", startDate: "2026-01-13", endDate: "2026-01-19", attendees: 110000, exhibitors: 4500,
    industry: "Gift / Home Goods", url: "https://www.americasmart.com",
    description: "Salon gift + home goods US. Retailers indépendants + chains + designers + showroom permanent.",
  },
  {
    slug: "viatec-vienna-2026", name: "ViaTec Vienna 2026", city: "Vienna", country: "AT", countryFlag: "🇦🇹",
    venue: "Messe Wien", startDate: "2026-09-15", endDate: "2026-09-18", attendees: 18000, exhibitors: 450,
    industry: "Transport / Mobility CEE", url: "https://www.viatec.at",
    description: "Salon transport + mobilité Europe centrale. Infrastructure routière + smart cities + EV charging.",
  },
  {
    slug: "biotechnica-hannover-2027", name: "Biotechnica Hannover 2027", city: "Hannover", country: "DE", countryFlag: "🇩🇪",
    venue: "Messe Hannover", startDate: "2027-10-05", endDate: "2027-10-07", attendees: 11000, exhibitors: 500,
    industry: "Biotech Europe", url: "https://www.biotechnica.de",
    description: "Salon biotech Europe. Equipment + reagents + pharma services + academia.",
  },
  {
    slug: "ipack-ima-milan-2027", name: "Ipack-Ima Milan 2027", city: "Milan", country: "IT", countryFlag: "🇮🇹",
    venue: "Fiera Milano", startDate: "2027-05-04", endDate: "2027-05-07", attendees: 60000, exhibitors: 1500,
    industry: "Packaging Italy", url: "https://www.ipackima.com",
    description: "Salon packaging + processing Italie. Machinerie + matériaux + tech industrielle food/pharma.",
  },
  {
    slug: "alimentaria-barcelona-2026", name: "Alimentaria Barcelona 2026", city: "Barcelona", country: "ES", countryFlag: "🇪🇸",
    venue: "Fira Gran Via", startDate: "2026-03-16", endDate: "2026-03-19", attendees: 90000, exhibitors: 4500,
    industry: "Food Spain", url: "https://www.alimentaria.com",
    description: "Salon F&B Espagne. Vins + huiles + jambons + olives + fruits secs. Distribution Europe + Latam.",
  },
  {
    slug: "mediterranean-renewable-energy-tunis-2026", name: "MENA Renewable Energy Conf Tunis 2026", city: "Tunis", country: "TN", countryFlag: "🇹🇳",
    venue: "Tunis Convention Center", startDate: "2026-05-19", endDate: "2026-05-21", attendees: 5000, exhibitors: 150,
    industry: "Renewable / MENA", url: "https://www.menaelec.com",
    description: "Salon renouvelables Méditerranée. Solaire + éolien + storage + transition énergétique Maghreb.",
  },
];

export function bySlug(slug: string): TradeShow | undefined {
  return TRADE_SHOWS.find((s) => s.slug === slug);
}

export function upcoming(): TradeShow[] {
  const now = new Date().toISOString().split("T")[0];
  return TRADE_SHOWS.filter((s) => s.startDate >= now).sort((a, b) =>
    a.startDate.localeCompare(b.startDate),
  );
}
