// YouTube transcript fetcher — uses YouTube's Innertube (mobile) API
// More reliable than scraping the watch page because the mobile API
// returns caption tracks in a stable JSON shape.
// No API key required.

const LANGUAGE_PRIORITY = ['fr', 'en', 'es', 'pt', 'ar', 'sw', 'zh'];

const INNERTUBE_URL = 'https://www.youtube.com/youtubei/v1/player?prettyPrint=false';
const ANDROID_CLIENT_VERSION = '20.10.38';
const ANDROID_USER_AGENT = `com.google.android.youtube/${ANDROID_CLIENT_VERSION} (Linux; U; Android 14)`;

export interface TranscriptResult {
  text: string;
  language: string;
  isAutoGenerated: boolean;
}

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string; // "asr" = auto-generated
}

/**
 * Query the Innertube player endpoint (ANDROID client) to list captions.
 */
async function fetchCaptionTracks(videoId: string): Promise<CaptionTrack[]> {
  const body = {
    context: {
      client: {
        clientName: 'ANDROID',
        clientVersion: ANDROID_CLIENT_VERSION,
      },
    },
    videoId,
  };
  const res = await fetch(INNERTUBE_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': ANDROID_USER_AGENT,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    throw new Error(`Innertube player ${res.status}`);
  }
  const data = (await res.json()) as {
    captions?: {
      playerCaptionsTracklistRenderer?: {
        captionTracks?: Array<{ baseUrl: string; languageCode: string; kind?: string }>;
      };
    };
  };
  const tracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  return Array.isArray(tracks) ? tracks : [];
}

function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_m, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_m, d) => String.fromCodePoint(parseInt(d, 10)));
}

/**
 * Download and parse a transcript XML.
 * YouTube returns one of two formats:
 *   1. <text start="..." dur="...">content</text>
 *   2. <p t="..." d="..."><s>word</s><s>word</s></p>  (srv3 style)
 */
async function downloadAndParse(baseUrl: string): Promise<string> {
  const res = await fetch(baseUrl, {
    headers: { 'User-Agent': ANDROID_USER_AGENT },
  });
  if (!res.ok) throw new Error(`track ${res.status}`);
  const xml = await res.text();

  // Try srv3 <p> format first
  const texts: string[] = [];
  const pMatches = xml.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/g);
  for (const m of pMatches) {
    const inner = m[1];
    const sMatches = [...inner.matchAll(/<s[^>]*>([^<]*)<\/s>/g)];
    const content = sMatches.length > 0
      ? sMatches.map((x) => x[1]).join('')
      : inner.replace(/<[^>]+>/g, '');
    const clean = decodeEntities(content).trim();
    if (clean) texts.push(clean);
  }
  if (texts.length > 0) return texts.join(' ').replace(/\s+/g, ' ').trim();

  // Fallback: <text> format
  const tMatches = xml.matchAll(/<text[^>]*>([^<]*)<\/text>/g);
  for (const m of tMatches) {
    texts.push(decodeEntities(m[1]));
  }
  return texts.join(' ').replace(/\s+/g, ' ').trim();
}

/**
 * Fetch a transcript, trying languages in priority order.
 * Returns null if no transcript is available.
 */
export async function fetchTranscript(videoId: string): Promise<TranscriptResult | null> {
  let tracks: CaptionTrack[];
  try {
    tracks = await fetchCaptionTracks(videoId);
  } catch (err) {
    console.warn(`[transcript] ${videoId}: ${(err as Error).message}`);
    return null;
  }
  if (tracks.length === 0) return null;

  // Sort: manual tracks first, then by language priority
  const sorted = [...tracks].sort((a, b) => {
    const aManual = a.kind !== 'asr' ? 0 : 1;
    const bManual = b.kind !== 'asr' ? 0 : 1;
    if (aManual !== bManual) return aManual - bManual;
    const aPriority = LANGUAGE_PRIORITY.indexOf(a.languageCode);
    const bPriority = LANGUAGE_PRIORITY.indexOf(b.languageCode);
    return (aPriority === -1 ? 99 : aPriority) - (bPriority === -1 ? 99 : bPriority);
  });

  for (const track of sorted) {
    try {
      const text = await downloadAndParse(track.baseUrl);
      if (text && text.length > 100) {
        return {
          text,
          language: track.languageCode,
          isAutoGenerated: track.kind === 'asr',
        };
      }
    } catch (err) {
      console.warn(`[transcript] ${videoId} ${track.languageCode}: ${(err as Error).message}`);
    }
  }
  return null;
}

/**
 * Batch fetch transcripts with concurrency limit.
 */
export async function fetchTranscriptsBatch(
  videoIds: string[],
  concurrency = 3,
): Promise<Map<string, TranscriptResult | null>> {
  const results = new Map<string, TranscriptResult | null>();
  const queue = [...videoIds];

  async function worker() {
    while (queue.length > 0) {
      const id = queue.shift();
      if (!id) return;
      try {
        const result = await fetchTranscript(id);
        results.set(id, result);
      } catch {
        results.set(id, null);
      }
    }
  }

  await Promise.all(Array.from({ length: concurrency }, worker));
  return results;
}
