-- Seed des 11 templates Incoterms 2020 · Vague 3 #6 · 2026-04-18
-- Idempotent (upsert sur primary key code).

insert into public.incoterms_templates (code, mode_scope, seller_duties, buyer_duties, risk_transfer, cost_transfer, template_text, version) values
('EXW', 'any_mode',
  '["Mettre la marchandise à disposition à ses locaux/usine.","Fournir facture commerciale + preuve de disposition."]'::jsonb,
  '["Charger la marchandise au lieu convenu.","Douane export + import + transport + assurance + livraison."]'::jsonb,
  'Chez le vendeur, marchandise mise à disposition (non chargée).',
  'Vendeur: rien. Acheteur: tout dès la mise à disposition.',
  'EXW place la quasi-totalité des obligations sur l''acheteur — mal adapté si export hors UE. Préférer FCA.',
  '2020'),
('FCA', 'any_mode',
  '["Livrer au transporteur désigné par l''acheteur au lieu convenu.","Dédouaner à l''export."]'::jsonb,
  '["Nommer le transporteur et supporter le fret principal.","Douane import + livraison finale."]'::jsonb,
  'À la remise au transporteur nommé par l''acheteur, au lieu convenu.',
  'Vendeur: jusqu''à la remise au transporteur + douane export. Acheteur: à partir de la prise en charge.',
  '',
  '2020'),
('CPT', 'any_mode',
  '["Contrat de transport jusqu''au lieu convenu.","Douane export + fret payé."]'::jsonb,
  '["Assurance (si souhaitée) à partir de la remise au premier transporteur.","Douane import + livraison finale."]'::jsonb,
  'À la remise au premier transporteur (même si le vendeur paie le fret jusqu''au lieu de destination convenu).',
  'Vendeur paie le fret jusqu''au lieu de destination convenu. Acheteur supporte le risque dès la remise au premier transporteur.',
  'Transfert du risque et transfert des coûts NE sont PAS au même endroit — piège classique.',
  '2020'),
('CIP', 'any_mode',
  '["Contrat de transport + assurance ICC A (niveau maximum depuis Incoterms 2020).","Douane export."]'::jsonb,
  '["Douane import + livraison finale."]'::jsonb,
  'À la remise au premier transporteur.',
  'Vendeur paie le fret + une assurance tous risques (ICC A) jusqu''au lieu de destination convenu.',
  'Incoterms 2020: niveau d''assurance pour CIP relevé de ICC C à ICC A (CIF reste ICC C).',
  '2020'),
('DAP', 'any_mode',
  '["Transport jusqu''au lieu convenu.","Douane export."]'::jsonb,
  '["Décharger la marchandise.","Douane import + taxes."]'::jsonb,
  'À la livraison au lieu convenu, marchandise mise à disposition (non déchargée).',
  'Vendeur: tout jusqu''au lieu convenu. Acheteur: déchargement + douane import.',
  '',
  '2020'),
('DPU', 'any_mode',
  '["Transport + déchargement au lieu convenu.","Douane export."]'::jsonb,
  '["Douane import + taxes."]'::jsonb,
  'À la livraison ET déchargement au lieu convenu.',
  'Vendeur: tout jusqu''au déchargement inclus. Acheteur: douane import.',
  'Seul Incoterm où le vendeur est obligé de décharger. Remplace DAT (2010).',
  '2020'),
('DDP', 'any_mode',
  '["Transport + douane export + douane import + taxes.","Livraison au lieu convenu."]'::jsonb,
  '["Décharger la marchandise."]'::jsonb,
  'À la livraison au lieu convenu, dédouanée à l''import (non déchargée).',
  'Vendeur: absolument tout, y compris droits et taxes import.',
  'Le plus contraignant pour le vendeur — à n''utiliser que si capacité à dédouaner dans le pays d''import.',
  '2020'),
('FAS', 'sea_waterway',
  '["Livrer la marchandise le long du navire au port convenu.","Douane export."]'::jsonb,
  '["Chargement + fret maritime + douane import."]'::jsonb,
  'À la mise le long du navire au port d''embarquement.',
  'Vendeur: jusqu''au quai. Acheteur: chargement + fret maritime + import.',
  '',
  '2020'),
('FOB', 'sea_waterway',
  '["Livrer et charger la marchandise à bord du navire désigné par l''acheteur.","Douane export."]'::jsonb,
  '["Fret maritime + assurance + douane import."]'::jsonb,
  'Quand la marchandise est chargée à bord du navire au port d''embarquement.',
  'Vendeur: jusqu''au chargement à bord. Acheteur: fret maritime + import.',
  '',
  '2020'),
('CFR', 'sea_waterway',
  '["Fret maritime + douane export."]'::jsonb,
  '["Assurance + déchargement + douane import."]'::jsonb,
  'Quand la marchandise est chargée à bord (même si le vendeur paie jusqu''au port d''arrivée).',
  'Vendeur: fret maritime payé jusqu''au port d''arrivée. Acheteur: assurance + déchargement + import.',
  '',
  '2020'),
('CIF', 'sea_waterway',
  '["Fret + assurance ICC C + douane export."]'::jsonb,
  '["Déchargement + douane import."]'::jsonb,
  'Quand la marchandise est chargée à bord.',
  'Vendeur: fret maritime + assurance (niveau minimum ICC C) jusqu''au port d''arrivée.',
  'Assurance min ICC C pour CIF (2020) — si plus couverture souhaitée, utiliser CIP.',
  '2020')
on conflict (code) do update set
  mode_scope = excluded.mode_scope,
  seller_duties = excluded.seller_duties,
  buyer_duties = excluded.buyer_duties,
  risk_transfer = excluded.risk_transfer,
  cost_transfer = excluded.cost_transfer,
  template_text = excluded.template_text,
  version = excluded.version,
  updated_at = now();
