-- Feel The Gap — Scale agents infrastructure
-- Tables for SEO Factory, Social Autopilot, AI Influencer Factory, Deal Flows

-- ── SEO Pages (generated by seo-factory.ts) ────────────────────────────────────
create table if not exists seo_pages (
  id              uuid primary key default gen_random_uuid(),
  slug            text unique not null,
  lang            text not null,
  country_iso     text references countries(id),
  product_slug    text not null,
  title           text not null,
  meta_description text,
  h1              text,
  content_html    text not null,
  keywords        text[] not null default '{}',
  views_count     int not null default 0,
  signups_from    int not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists idx_seo_pages_lang on seo_pages(lang);
create index if not exists idx_seo_pages_country on seo_pages(country_iso);

-- ── Social Posts (generated by social-autopilot.ts) ────────────────────────────
create table if not exists social_posts (
  id              uuid primary key default gen_random_uuid(),
  lang            text not null,
  platform        text not null check (platform in ('linkedin', 'twitter', 'instagram', 'tiktok', 'youtube')),
  content_type    text not null check (content_type in ('market_insight', 'data_drop', 'success_story', 'cta', 'product_showcase')),
  persona_handle  text,   -- references ai_influencer_personas.handle if posted by AI persona
  text            text not null,
  hashtags        text[] not null default '{}',
  media_urls      text[] not null default '{}',
  cta_url         text,
  scheduled_at    timestamptz,
  published_at    timestamptz,
  status          text not null default 'pending' check (status in ('pending', 'scheduled', 'published', 'failed')),
  -- Performance metrics (updated by analytics)
  impressions     int not null default 0,
  clicks          int not null default 0,
  engagements     int not null default 0,
  signups_attributed int not null default 0,
  created_at      timestamptz not null default now()
);
create index if not exists idx_social_posts_status on social_posts(status);
create index if not exists idx_social_posts_lang on social_posts(lang);
create index if not exists idx_social_posts_persona on social_posts(persona_handle);

-- ── AI Influencer Personas (generated by influencer-factory.ts) ────────────────
create table if not exists ai_influencer_personas (
  id              uuid primary key default gen_random_uuid(),
  handle          text unique not null,
  lang            text not null,
  display_name    text not null,
  bio             text,
  niche           text not null,
  vertical        text not null,
  region          text,
  archetype_id    int,
  audience_size   int not null default 0,
  engagement_rate numeric not null default 0,
  platforms       text[] not null default '{}',
  content_pillars text[] not null default '{}',
  voice_traits    text[] not null default '{}',
  posting_frequency text,
  example_post    text,
  -- Performance tracking
  total_posts     int not null default 0,
  total_impressions bigint not null default 0,
  total_clicks    int not null default 0,
  total_signups   int not null default 0,
  revenue_attributed_eur numeric not null default 0,
  -- Auto-optimization
  effectiveness_score numeric not null default 50,  -- 0-100, updated by auto-optimizer
  last_optimized_at timestamptz,
  status          text not null default 'active' check (status in ('active', 'paused', 'retired')),
  created_at      timestamptz not null default now()
);
create index if not exists idx_ai_personas_lang on ai_influencer_personas(lang);
create index if not exists idx_ai_personas_niche on ai_influencer_personas(niche);

-- ── Deal Flows (for investor personas) ─────────────────────────────────────────
create table if not exists deal_flows (
  id              uuid primary key default gen_random_uuid(),
  -- Deal info
  title           text not null,
  slug            text unique not null,
  sector          text not null,
  subsector       text,
  stage           text not null check (stage in ('seed', 'series_a', 'series_b', 'growth', 'bridge', 'ipo_ready')),
  -- Geography
  country_iso     text references countries(id),
  region          text,
  -- Financials
  raise_amount_eur numeric not null,
  valuation_pre_eur numeric,
  equity_offered_pct numeric,
  revenue_current_eur numeric,
  revenue_target_y3_eur numeric,
  ebitda_margin_pct numeric,
  -- Team
  founders_summary text,
  team_size       int,
  -- Product
  product_description text not null,
  traction_summary text,
  competitive_advantage text,
  -- Impact
  impact_metrics  jsonb not null default '{}'::jsonb,
  sdg_goals       text[] not null default '{}',
  -- Display
  hero_image_url  text,
  pitch_deck_url  text,
  -- Meta
  status          text not null default 'active' check (status in ('active', 'funded', 'closed', 'archived')),
  featured        boolean not null default false,
  views_count     int not null default 0,
  interest_count  int not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists idx_deal_flows_sector on deal_flows(sector);
create index if not exists idx_deal_flows_country on deal_flows(country_iso);
create index if not exists idx_deal_flows_stage on deal_flows(stage);

-- ── Auto-Optimizer Log (tracks all AI optimization decisions) ──────────────────
create table if not exists auto_optimizer_log (
  id              uuid primary key default gen_random_uuid(),
  agent_name      text not null,
  action_type     text not null,  -- 'prompt_update', 'persona_pause', 'pricing_change', 'churn_intervention'
  target_id       text,           -- ID of the entity being optimized
  before_state    jsonb,
  after_state     jsonb,
  reason          text not null,
  impact_estimate text,
  executed        boolean not null default false,
  created_at      timestamptz not null default now()
);

-- RLS — open read for authenticated, admin-only write via service key
alter table seo_pages enable row level security;
create policy "seo_public_read" on seo_pages for select using (true);

alter table social_posts enable row level security;
create policy "social_public_read" on social_posts for select using (true);

alter table ai_influencer_personas enable row level security;
create policy "personas_public_read" on ai_influencer_personas for select using (true);

alter table deal_flows enable row level security;
create policy "deals_public_read" on deal_flows for select using (true);

alter table auto_optimizer_log enable row level security;
create policy "optimizer_admin_read" on auto_optimizer_log for select using (true);

comment on table seo_pages is 'Landing pages SEO générées par seo-factory.ts — 300K+ pages (pays × produit × 15 langues)';
comment on table social_posts is 'Posts social media générés par social-autopilot.ts — 135+ posts/jour × 15 langues';
comment on table ai_influencer_personas is 'Personas IA influenceurs générés par influencer-factory.ts — 300 personas (20 archétypes × 15 langues)';
comment on table deal_flows is 'Deal flows pour investisseurs — 100+ deals variés tous secteurs';
comment on table auto_optimizer_log is 'Journal des décisions d auto-optimisation du méta-agent';
