-- Entrepreneur Scout — Personalized Demo System
-- Generates demo pages for potential entrepreneurs before outreach

create table if not exists entrepreneur_demos (
  id              uuid primary key default gen_random_uuid(),
  token           text unique not null,         -- 12-char token for /demo/[token]
  -- Entrepreneur profile
  full_name       text not null,
  company_name    text,
  email           text,
  linkedin_url    text,
  country_iso     text,
  city            text,
  sector          text,                         -- 'agriculture', 'textile', 'food_processing', etc.
  product_focus   text[],                       -- produits identifiés
  -- Generated demo content
  business_plan   jsonb,                        -- enriched 3-scenario plan
  opportunities   jsonb default '[]'::jsonb,    -- matched opportunities
  investors       jsonb default '[]'::jsonb,    -- matched investor profiles
  market_data     jsonb,                        -- relevant country data
  hero_message    text,                         -- personalized headline
  -- Tracking
  status          text not null default 'generated' check (status in (
    'generating',     -- en cours de génération
    'generated',      -- prêt à envoyer
    'sent',           -- outreach envoyé
    'viewed',         -- entrepreneur a vu la page
    'engaged',        -- a interagi (cliqué CTA)
    'converted',      -- s'est inscrit sur FTG
    'expired'         -- plus de 30 jours sans action
  )),
  views_count     int default 0,
  first_viewed_at timestamptz,
  converted_at    timestamptz,
  user_id         uuid,                         -- FK profiles si converti
  -- Outreach
  outreach_channel text check (outreach_channel in ('email', 'linkedin', 'whatsapp')),
  outreach_sent_at timestamptz,
  outreach_opened  boolean default false,
  -- Source
  source          text default 'scout',         -- 'scout', 'manual', 'referral'
  source_detail   text,                         -- e.g. 'linkedin_search', 'incubator_xyz'
  -- Meta
  expires_at      timestamptz default now() + interval '90 days',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_demos_token on entrepreneur_demos(token);
create index if not exists idx_demos_status on entrepreneur_demos(status);
create index if not exists idx_demos_country on entrepreneur_demos(country_iso);
create index if not exists idx_demos_sector on entrepreneur_demos(sector);

-- Metrics aggregation
create table if not exists scout_metrics (
  id              uuid primary key default gen_random_uuid(),
  date            date not null unique,
  demos_generated int default 0,
  outreach_sent   int default 0,
  demos_viewed    int default 0,
  demos_engaged   int default 0,
  demos_converted int default 0,
  conversion_rate numeric default 0,
  top_sector      text,
  top_country     text,
  created_at      timestamptz not null default now()
);

-- RLS
alter table entrepreneur_demos enable row level security;
create policy "demos_public_read" on entrepreneur_demos for select using (true);
create policy "demos_admin_write" on entrepreneur_demos for all using (true);

alter table scout_metrics enable row level security;
create policy "scout_metrics_admin" on scout_metrics for all using (true);

comment on table entrepreneur_demos is 'Personalized demo pages generated by entrepreneur-scout before outreach. Token = public URL slug.';
