-- Cron health observability — every cron writes a heartbeat row,
-- a registry declares expected interval, and a view computes liveness.
-- Used by /admin/cron-health on Command Center.

create table if not exists public.cron_runs (
  id              bigint generated by default as identity primary key,
  cron_name       text not null,
  host            text not null default 'vps-1',
  started_at      timestamptz not null default now(),
  finished_at     timestamptz,
  duration_ms     int generated always as (
    case when finished_at is null then null
         else (extract(epoch from (finished_at - started_at)) * 1000)::int
    end
  ) stored,
  success         boolean,
  error_msg       text,
  items_processed int default 0,
  metadata        jsonb
);

create index if not exists cron_runs_name_started_idx
  on public.cron_runs (cron_name, started_at desc);

create index if not exists cron_runs_name_success_started_idx
  on public.cron_runs (cron_name, success, started_at desc);

create table if not exists public.cron_registry (
  cron_name           text primary key,
  schedule            text,                  -- crontab expression for display
  expected_interval_s int not null,          -- normal time between runs
  alert_after_s       int not null,          -- silence threshold for alerts
  host                text default 'vps-1',  -- where it runs (vps-1, vercel, etc.)
  repo                text,                  -- repo it lives in
  description         text,
  active              boolean not null default true,
  created_at          timestamptz not null default now()
);

create or replace view public.cron_health as
with last_runs as (
  select distinct on (cron_name)
    cron_name,
    started_at  as last_run_at,
    finished_at as last_finished_at,
    success     as last_success,
    error_msg   as last_error,
    duration_ms as last_duration_ms
  from public.cron_runs
  order by cron_name, started_at desc
),
agg_24h as (
  select
    cron_name,
    count(*)                                                              as runs_24h,
    count(*) filter (where success is true)                               as success_24h,
    count(*) filter (where success is false)                              as fail_24h,
    coalesce(avg(duration_ms) filter (where success is true), 0)::int     as avg_duration_ms_24h
  from public.cron_runs
  where started_at > now() - interval '24 hours'
  group by cron_name
)
select
  r.cron_name,
  r.schedule,
  r.expected_interval_s,
  r.alert_after_s,
  r.host,
  r.repo,
  r.description,
  r.active,
  l.last_run_at,
  l.last_finished_at,
  l.last_success,
  l.last_error,
  l.last_duration_ms,
  coalesce(a.runs_24h, 0)            as runs_24h,
  coalesce(a.success_24h, 0)         as success_24h,
  coalesce(a.fail_24h, 0)            as fail_24h,
  case when coalesce(a.runs_24h, 0) > 0
       then round(100.0 * a.success_24h / a.runs_24h, 1)
       else null
  end                                as success_rate_pct_24h,
  coalesce(a.avg_duration_ms_24h, 0) as avg_duration_ms_24h,
  extract(epoch from (now() - l.last_run_at))::int as silent_for_s,
  case
    when l.last_run_at is null                                            then 'never_ran'
    when extract(epoch from (now() - l.last_run_at)) > r.alert_after_s    then 'silent'
    when coalesce(a.runs_24h, 0) > 0
         and (a.fail_24h::float / nullif(a.runs_24h, 0)) > 0.25            then 'failing'
    when l.last_success is false                                          then 'last_failed'
    else 'healthy'
  end as status
from public.cron_registry r
left join last_runs l using (cron_name)
left join agg_24h a   using (cron_name)
where r.active is true;

alter table public.cron_runs     enable row level security;
alter table public.cron_registry enable row level security;

drop policy if exists cron_runs_service_all     on public.cron_runs;
drop policy if exists cron_registry_service_all on public.cron_registry;

create policy cron_runs_service_all
  on public.cron_runs for all
  to service_role
  using (true) with check (true);

create policy cron_registry_service_all
  on public.cron_registry for all
  to service_role
  using (true) with check (true);

-- Seed registry with known crons (idempotent)
insert into public.cron_registry (cron_name, schedule, expected_interval_s, alert_after_s, host, repo, description) values
  ('ftg-scout-loop',           '* * * * * (loop 60s)',     90,    600,  'vps-1', 'feel-the-gap',  'FTG entrepreneur scout — primary loop'),
  ('ftg-scout-loop-2',         '* * * * * (loop 75s)',     120,   600,  'vps-1', 'feel-the-gap',  'FTG entrepreneur scout — secondary loop'),
  ('ftg-scout-autoreseeder',   '*/5 * * * *',              360,   1200, 'vps-1', 'feel-the-gap',  'FTG scout queue reseeder'),
  ('ofa-enrich',               '0 7 * * *',                86400, 90000,'vps-1', 'site-factory',  'OFA Google Places review enrichment'),
  ('ftg-marketplace-state',    '*/5 * * * *',              300,   900,  'vps-1', 'feel-the-gap',  'FTG marketplace_state recompute'),
  ('ftg-mass-generator',       '*/5 * * * *',              360,   1200, 'vps-1', 'feel-the-gap',  'FTG LLM mass-generator (scout queue)'),
  ('ftg-dir-to-demos',         '*/5 * * * *',              360,   1200, 'vps-1', 'feel-the-gap',  'FTG directory → demo sites generator'),
  ('ftg-matcher',              '* * * * * (loop 1800s)',   2100,  4200, 'vps-1', 'feel-the-gap',  'FTG buyer/seller matcher')
on conflict (cron_name) do update set
  schedule            = excluded.schedule,
  expected_interval_s = excluded.expected_interval_s,
  alert_after_s       = excluded.alert_after_s,
  host                = excluded.host,
  repo                = excluded.repo,
  description         = excluded.description,
  active              = true;
