-- Queue table for the autonomous portfolio page builder.
-- Vercel cron /api/cron/portfolio-build claims jobs from here, generates
-- the page TSX via cascade LLM, pushes to GitHub, and marks done.

create table if not exists public.portfolio_build_jobs (
  id              bigint generated by default as identity primary key,
  product_slug    text not null,
  page_type       text not null check (page_type in (
    'home','services','offres','faq','contact','demo',
    'cgu','cgv','mentions-legales','privacy'
  )),
  brief           jsonb default '{}'::jsonb,
  status          text not null default 'pending' check (status in (
    'pending','processing','done','failed'
  )),
  attempts        int not null default 0,
  last_error      text,
  claimed_at      timestamptz,
  finished_at     timestamptz,
  generated_path  text,
  commit_sha      text,
  html_url        text,
  provider        text,
  cost_usd        numeric(10,4),
  priority        int not null default 50,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (product_slug, page_type, status)
);

create index if not exists portfolio_build_jobs_status_idx
  on public.portfolio_build_jobs (status, priority desc, id);

create index if not exists portfolio_build_jobs_product_idx
  on public.portfolio_build_jobs (product_slug, page_type);

create or replace function public.touch_portfolio_build_jobs_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end$$;

drop trigger if exists portfolio_build_jobs_touch on public.portfolio_build_jobs;
create trigger portfolio_build_jobs_touch
  before update on public.portfolio_build_jobs
  for each row execute function public.touch_portfolio_build_jobs_updated_at();

alter table public.portfolio_build_jobs enable row level security;

drop policy if exists portfolio_build_jobs_service_all on public.portfolio_build_jobs;
create policy portfolio_build_jobs_service_all
  on public.portfolio_build_jobs for all
  to service_role
  using (true) with check (true);

grant usage on schema public to anon, authenticated, service_role;
grant all on public.portfolio_build_jobs to anon, authenticated, service_role;
grant all on sequence public.portfolio_build_jobs_id_seq to anon, authenticated, service_role;

-- Register the new crons in cron_registry so /admin/cron-health sees them.
insert into public.cron_registry (cron_name, schedule, expected_interval_s, alert_after_s, host, repo, description) values
  ('portfolio-build',      '12 6 * * *',   86400, 90000, 'vercel', 'command-center', 'Vercel daily fallback — drains portfolio_build_jobs queue'),
  ('portfolio-build-tick', '*/30 * * * *', 1800,  3900,  'vps-1',  'command-center', 'VPS tick — pings /api/cron/portfolio-build every 30 min')
on conflict (cron_name) do update set
  schedule = excluded.schedule,
  expected_interval_s = excluded.expected_interval_s,
  alert_after_s = excluded.alert_after_s,
  host = excluded.host,
  repo = excluded.repo,
  description = excluded.description,
  active = true;

notify pgrst, 'reload schema';
